### ISSUE TITLE
Multi-threaded Maven issue

### ISSUE THREAD

**Issue by adamretter** [jacoco/jacoco#1042]
### Steps to reproduce

* JaCoCo version:  0.8.5
* Operating system: macOS
* Tool integration: Maven 3.6.3
* Complete executable reproducer: https://github.com/adamretter/exist/tree/feature/code-coverage (Travis report: https://travis-ci.com/github/eXist-db/exist/jobs/313620334#L1724)
* Steps:

```
git clone --single-branch --branch feature/code-coverage https://github.com/adamretter/exist.git
cd exist
mvn -T 2C test jacoco:report
```

### Expected behaviour

The tests pass and the build completes.

### Actual behaviour
```
[INFO] Results:
[INFO]
[WARNING] Tests run: 4676, Failures: 0, Errors: 0, Skipped: 102
[INFO]
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.5:report (default-cli) @ exist-core ---
[INFO] Loading execution data file /Users/aretter/tmp-code/exist-for-release/exist-core/target/jacoco.exec

[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report (default-cli) on project exist-core: An error has occurred in JaCoCo report generation.: Error while creating report: Unknown block type c0. -> [Help 1]
```

I believe this is a concurrency issue as removing the mvn arg `-T 2C` causes the build to complete without any JaCoCo errors.

The `jacoco-maven-plugin` claims that it is `threadSafe = true` (see: https://github.com/jacoco/jacoco/blob/master/jacoco-maven-plugin/src/org/jacoco/maven/ReportMojo.java#L30), so I would expect this to work with `-T 2C`.

**Comment by Godin** [comment]
Even without `-T 2C` you can notice that after execution of `mvn clean test`
sometimes there is thread dump `exist-core/target/surefire-reports/*jvmRun*.dump`

```
"surefire-forkedjvm-last-ditch-daemon-shutdown-thread-30s"
   java.lang.Thread.State: RUNNABLE
        at java.management@10.0.2/sun.management.ThreadImpl.getThreadInfo1(Native Method)
        at java.management@10.0.2/sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:190)
        at app//org.apache.maven.surefire.booter.ForkedBooter.generateThreadDump(ForkedBooter.java:546)
        at app//org.apache.maven.surefire.booter.ForkedBooter.access$400(ForkedBooter.java:68)
        at app//org.apache.maven.surefire.booter.ForkedBooter$7.run(ForkedBooter.java:414)
        at java.base@10.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base@10.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@10.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base@10.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base@10.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@10.0.2/java.lang.Thread.run(Thread.java:844)

"Thread-0"
   java.lang.Thread.State: RUNNABLE
        at app//org.jacoco.agent.rt.internal_43f5073.output.FileOutput.writeExecutionData(FileOutput.java:56)
        at app//org.jacoco.agent.rt.internal_43f5073.Agent.shutdown(Agent.java:145)
        at app//org.jacoco.agent.rt.internal_43f5073.Agent$1.run(Agent.java:58)
```

`org.jacoco.agent.rt.internal_43f5073.output.FileOutput.writeExecutionData(FileOutput.java:56)`
indicates that JVM shutdown hook registered by JaCoCo agent started to write to the file

`org.apache.maven.surefire.booter.ForkedBooter$7.run(ForkedBooter.java:414)`
indicates that at the same time `maven-surefire-plugin` forcibly halts JVM

https://github.com/apache/maven-surefire/blob/surefire-3.0.0-M4/surefire-booter/src/main/java/org/apache/maven/surefire/booter/ForkedBooter.java#L414-L416

https://github.com/apache/maven-surefire/blob/surefire-3.0.0-M4/surefire-booter/src/main/java/org/apache/maven/surefire/booter/ForkedBooter.java#L337-L346

`Unknown block type` during execiton of `org.jacoco:jacoco-maven-plugin:0.8.5:report`
indicates corruption of the file due to the above incomplete write.

You can also see that execution of
`mvn -Djacoco.skip -Dsurefire.exitTimeout=600`
is stuck for 600 seconds at the end of tests in `exist-core`,
showing that even without JaCoCo `maven-surefire-plugin` forcibly halts forked JVMs.

I suspect that this is caused by something in your tests or main code that use embedded Jetty - the above command won't be stuck and corruption of JaCoCo file also does not happen when `org.exist.management.JmxRemoteTest` and `org.exist.http.urlrewrite.URLRewritingTest` are excluded from execution.

All in all, please fix your code - JVMs with tests should terminate gracefully with the execution of shutdown hook registered by JaCoCo.

----

P.S. Strange that `maven-surefire-plugin` doesn't trigger shutdown hooks in advance of halting as described on page http://maven.apache.org/surefire/maven-surefire-plugin/examples/shutdown.html

> After the test-set has completed, the process executes `java.lang.System.exit(0)` which starts shutdown hooks. At this point the process may run next 30 seconds until all non daemon Threads die. After the period of time has elapsed, the process kills itself by `java.lang.Runtime.halt(0)`. The timeout of 30 seconds can be customized by configuration parameter `forkedProcessExitTimeoutInSeconds`.

but this should be reported to developers of `maven-surefire-plugin` (CC @Tibor17).

**Comment by adamretter** [comment]
@Godin Wow thanks for the comprehensive reply! It looks like you really dug into this, I very much appreciate you taking your time to look into ity.

I will try and digest this and investigate in the next few days :-)
