### ISSUE TITLE
Jacoco 0.8.5 doesn't show code coverage with PowerMock 2.0.7

### ISSUE THREAD

**Issue by KiranBolaj1** [jacoco/jacoco#1065]
Hi,

I am unable to see code coverage for the test classes which have written.

I use following versions -
Jacoco - 0.8.5
PowerMock - 2.0.7
Jdk - 11
maven-surefire-plugin - 2.22.0

Can you please help me with this?

**Comment by marchof** [comment]
@KiranBolaj1 Please provide the information in out bug template if you think you actually discovered a bug. Questions are only answered at out mailing list: https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Here is the information you must provide if you want us to investigate your issue:

### Steps to reproduce

* JaCoCo version:  (from right bottom corner of JaCoCo report)
* Operating system:
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

### Expected behaviour

### Actual behaviour

(In case of exceptions provide FULL STACKTRACE)

**Comment by Godin** [comment]
In absence of complete executable reproducer one can only wonder whether you carefully read PowerMock documentation - https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo#offline-instrumentation
