### ISSUE TITLE
Is it possible to Use jacoco multiple times by java API invoking

### ISSUE THREAD

**Issue by cuixiaoyiyi** [jacoco/jacoco#1071]
I have noticed that jacoco recommends the script or command line mode when using.
Is it possible to call by API? 

Now when the instrument is executed, continue to execute the report (of course, JUnit execution will be inserted between them), the coverage rate is 0 with Main.main invoked by java. 
If the command line is used after the instrument is executed, there will be no such problem. 

Is there  a method similar to reset so that we can use the Java API to perform the task instead of script or command line multiple times  in a same process ( or program )?

**Comment by Godin** [comment]
First of all please carefully study documentation before asking questions
https://www.jacoco.org/jacoco/trunk/doc/

Where you can find
https://www.jacoco.org/jacoco/trunk/doc/api/org/jacoco/agent/rt/package-summary.html

And please don't use issue tracker to ask questions, because there is forum for this
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Where such question was already answered multiple times, e.g. for one of examples
https://groups.google.com/g/jacoco/c/SgryO8aLPgE/m/zJ0X3XasBQAJ
