### ISSUE TITLE
jacoco.exec file Very large

### ISSUE THREAD

**Issue by liangshaoJY** [jacoco/jacoco#1112]
jacoco version: 0.8.4

dump settings 

use ant    in build.xml

```
<target name="dump">
      <jacoco:dump address="${server_ip}" reset="false" destfile="${jacocoexecPath}" port="${server_port}" append="true"/>
</target>
```
file size
-rw-r--r-- 1 root root 1.1G Oct 21 06:13 jacoco.exec

How can this be avoided

**Comment by marchof** [comment]
This is indeed big. Hard to tell what the reason is without more context information. Maybe `append="true"` will increase the file size over time because it is never deleted?

Anyways, our mailing list is the place to ask questions.

**Comment by Godin** [comment]
Each execution of `dump` with `append="true"` appends a new session to the `destfile`.

Depending on what you're doing with dumps, you can choose one or many of the following
* use `reset="true"` so that new sessions will contain only data since the previous dump
* and/or use `append="false"` so that `destfile` will be overridden
* and/or remove `destfile` prior to `dump`
* and/or use `merge` after `dump` to merge information about the same classes form multiple sessions into one session
* and/or use agent options `includes`/`excludes` to choose classes that will be present in the sessions

Documentation about all these options available at https://www.jacoco.org/jacoco/trunk/doc/

**Comment by patric-r** [comment]
We've had the same problem. Using append by tenthousands of java executions and ending up with an 8 GB(!) jacoco.exec file.

By the comment of @Godin I realized that you can use jacoco merge not only for merging several javoco.exec files **but also for compacting a large one**!
In our case, file size reduced to 1.5MB and ecl-emma was finally able to import this within a few seconds.

This should be clearly stated in the documentation I'm sure many users are not aware of this.

**Comment by marchof** [comment]
@patric-r Can you please have a look at #1356? Does this make is clearer?

**Comment by patric-r** [comment]
@marchof Thanks, this is perfect!
