### ISSUE TITLE
Consider adding configuration for the ProbeArrayStrategy

### ISSUE THREAD

**Issue by cushon** [jacoco/jacoco#1151]
Starting in 0.8.4, jacoco uses condy when instrumenting Java 11+ class files: https://github.com/jacoco/jacoco/pull/845, https://github.com/jacoco/jacoco/commit/36b4e9c7103441d556a1667b4485960f5bdfeff8

Although condy was introduced in Java 11 in ([JEP 309](https://openjdk.java.net/jeps/309)), no Java 11 language features use it, so the bytecode present in the JDK 11 libraries or produced by `javac -target 11` does not use condy. As a result, not all bytecode tools have full support for condy when processing Java 11 class files. It looks like there have been a few related reports of issues with other bytecode processing tools, e.g. jMockit (#896), AspectJ (#909), PowerMock (#961).

The example of this I encountered is that Android [d8](https://developer.android.com/studio/command-line/d8) tool does not yet support constant dynamic: https://issuetracker.google.com/issues/178172809

The ideal long-term solution is for all tools that process bytecode to be updated to handle condy, but that will take time, and until that happens it will leave some users stuck on jacoco 0.8.3.

In the short term, would you consider adding configuration to jacoco to allow choosing `InterfaceFieldProbeArrayStrategy` instead of `CondyProbeArrayStrategy` even when processing Java 11 bytecode?

**Comment by dsuresh-ap** [comment]
Is there any ETA on this? Otherwise we cannot upgrade to Kotlin 1.5.x using Jacoco 0.8.3.

**Comment by marchof** [comment]
@dsuresh-ap Thanks for the heads-up on this ticket!

To be honest we will probably never implement this. More config options produce more problems and questions we're unable to handle here. This should rather be fixed in the other tools who do not handle bytecode correctly.

**Comment by cushon** [comment]
Thanks @marchof for triaging the bug, I understand the desire to not support additional configuration options.

As an FYI, in this specific case the use of condy is causing problems that have resulted in a couple of projects maintaining forks of jacoco with the logic that uses `constantdynamic` disabled:

* https://android.googlesource.com/platform/external/jacoco/+/0d5db7bcb686284b47bd393f364b3691a81cdab5%5E%21/
* https://github.com/bazelbuild/bazel/blob/master/third_party/java/jacoco/0001-Disable-use-of-constant-dynamic-bytecode.patch

I agree that the ideal long-term solution is for all tools that process bytecode to be updated to handle condy, but in practice support for the latest bytecode features takes time and will be more ubiquitous once javac starts emitting bytecode that uses the new feature.

**Comment by balgillo** [comment]
Thanks @cushon for sharing those links.  I support your call for jacoco to have a no-condy option.

Our project is stuck on old JMockit version 1.35 because newer "minor" versions of JMockit have completely removed key features that our mature suite of unit tests rely on.  There's an [open PR to fix the condy issue in JMockit](https://github.com/jmockit/jmockit1/pull/665), but still that won't help us because we can't upgrade without major rework.  Meanwhile, if we rebuild jacoco with the [0001-Disable-use-of-constant-dynamic-bytecode.patch](https://github.com/bazelbuild/bazel/blob/master/third_party/java/jacoco/0001-Disable-use-of-constant-dynamic-bytecode.patch) you shared, it completely fixes the problem.

We would much prefer to pass a configuration parameter to jacoco than fork the codebase!

**Comment by sgjesse** [comment]
Support for JaCoCo use of condy was added to d8 some time ago, and is supported from AGP 7.1 (Android Studio Bumblebee).
