### ISSUE TITLE
a minor release for can use jdk17?

### ISSUE THREAD

**Issue by XenoAmess** [jacoco/jacoco#1157]
asm 9.1 addrf supports for jdk 17, so I wonder, if we jacoco can release a minor release for people who wanna use jdk17 with jacoco?
thanks.

**Comment by Godin** [comment]
You can already use released JaCoCo 0.8.6 with JDK 17 Early Access Builds as long as analysed by JaCoCo classes are not compiled into Java 17 bytecode.

Otherwise please see https://www.jacoco.org/jacoco/trunk/doc/faq.html

> ### When will feature X be released?
> JaCoCo is maintained by volunteers in their free time. Since we cannot guarantee free capacity, we do not commit to particular release dates. Typically, you can expect a couple of releases every year.
>
> In the [change log](https://www.jacoco.org/jacoco/trunk/doc/changes.html), you can see all features that have been implemented in master branch and will be available with the next release. And in the meantime you can test latest build of master branch ([Maven SNAPSHOT](https://www.jacoco.org/jacoco/trunk/doc/repo.html)) and provide feedback to us.

Most likely there will be JaCoCo release after JDK 16 release this month.
