### ISSUE TITLE
Don't shade in ASM

### ISSUE THREAD

**Issue by garydgregory** [jacoco/jacoco#1200]
It would be best to stop shading ASM since this creates an impossible dependency to update when ASM supports a new version of Java or provides a fix in a new version.

**Comment by marchof** [comment]
ASM is only shaded in the JaCoCo Java agent which is used at runtime. This must be a single JAR file. As we don't want to require additional dependencies for our users beside adding the JAR file we decided to add ASM to it. We also rename the packages to avoid any conflicts with ASM versions used by the application under test.

So this is by design and we cannot change this.
