### ISSUE TITLE
Coverage report HTML line highlighting issue for very long file

### ISSUE THREAD

**Issue by dhendriks** [jacoco/jacoco#1228]
### Steps to reproduce

* JaCoCo version: 0.8.7
* Operating system: Linux
* Tool integration: Maven
* Complete executable reproducer: https://gitlab.eclipse.org/eclipse/escet/escet/-/merge_requests/160
* Steps: Running the build on Jenkins, producing a code coverage report

### Expected behaviour

Lines beyond line 55543 are highlighted where relevant. Comments and imports are not highlighted.

### Actual behaviour

No lines beyond line 55543 are highlighted (the generated Java file has 100K+ lines):

![image](https://user-images.githubusercontent.com/375606/135904056-9fa34413-eba9-4087-8a98-ab6ddca3289c.png)

Comments and imports are highlighted at the beginning of the file:

![image](https://user-images.githubusercontent.com/375606/135904076-c438a019-a66f-44e0-9ffe-24d2325ec4d4.png)

It feels a bit like something overflows, and then starts highlighting from the beginning of the file?

Jenkins build: https://ci.eclipse.org/escet/job/ESCET%20build/job/34-add-test-code-coverage-reporting-to-ide-and-build/5/

Problematic report: https://ci.eclipse.org/escet/job/ESCET%20build/job/34-add-test-code-coverage-reporting-to-ide-and-build/5/artifact/releng/org.eclipse.escet.releng.tests/target/eclipse-escet-jacoco-aggregate.zip

Within the report zip, the problem is visible for this file: `eclipse-escet-jacoco-aggregate/org.eclipse.escet.cif.parser/org.eclipse.escet.cif.parser/CifParser.java.html#L5549`

**Comment by Godin** [comment]
JaCoCo performs analysis of bytecode in class-files to obtain information about line numbers.

If you'll have a look at your `CifParser.class` in `org.eclipse.escet.cif.parser_0.4.0.v20211003-191028-dev.jar` from https://ci.eclipse.org/escet/job/ESCET%20build/job/34-add-test-code-coverage-reporting-to-ide-and-build/5/artifact/products/org.eclipse.escet.product/target/products/eclipse-escet-incubation-dev-linux.gtk.x86_64.tar.gz
you can notice that output of

```
javap -v -p CifParser.class | grep line
```

does not contain information about line numbers above `65534`

> It feels a bit like something overflows, and then starts highlighting from the beginning of the file

indeed you can see

```
        line 65534: 1434
        line 3: 1435
        line 4: 1449
```

According to [The Java Virtual Machine Specification chapter 4.7.12 about The LineNumberTable Attribute](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4.7.12)

> The value of the line_number item gives the corresponding line number in the original source file.

and stored using `u2` data type, which is unsigned two-bytes according to [the beginning of chapter 4](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4)

> data types u1, **u2**, and u4 to represent an unsigned one-, **two**-, or four-**byte** quantity, respectively

so that compiler can preserve in class-files only line numbers up to 65535.
And JaCoCo displays line numbers exactly as compiler encoded them into class-files.

----

Why overflow is permitted during compilation is a question to the developers of compiler that you use.
For example using OpenJDK `javac` versions `1.7.0_67`, `1.8.0_242`, `11.0.6` and `17` for

```
class Example {
    public static void main (String[] args) {
        System.out.println(); // line 65535
        System.out.println(); // line 65536
    }
}
```

```
javac -g Example.java
javap -v -p Example.class
```

shows

```
  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=1, locals=1, args_size=1
         0: getstatic     #7                  // Field java/lang/System.out:Ljava/io/PrintStream;
         3: invokevirtual #13                 // Method java/io/PrintStream.println:()V
         6: getstatic     #7                  // Field java/lang/System.out:Ljava/io/PrintStream;
         9: invokevirtual #13                 // Method java/io/PrintStream.println:()V
        12: return
      LineNumberTable:
        line 65535: 0
```

so seems that `javac` simply stops embedding into bytecode information about line numbers above 65535.

While using ECJ compiler version `3.27.0`

```
java -jar ecj-3.27.0.jar -g Example.java
javap -v -p Example.class
```

shows

```
  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=1, locals=1, args_size=1
         0: getstatic     #13                 // Field java/lang/System.out:Ljava/io/PrintStream;
         3: invokevirtual #19                 // Method java/io/PrintStream.println:()V
         6: getstatic     #13                 // Field java/lang/System.out:Ljava/io/PrintStream;
         9: invokevirtual #19                 // Method java/io/PrintStream.println:()V
        12: return
      LineNumberTable:
        line 65535: 0
        line 0: 6
        line 1: 12
```
