### ISSUE TITLE
Outdated Dependency -> org.codehaus.plexus:plexus-utils-3.0.2

### ISSUE THREAD

**Issue by asalsi** [jacoco/jacoco#1401]
Please update the following dependency to a supported version with no security flaws:
org.codehaus.plexus:plexus-utils-3.0.2

### Steps to reproduce

* JaCoCo version:  (0.8.8)
* Operating system: MAC OSX
* Tool integration: Maven 
* Complete executable reproducer: N/A
* Steps: N/A

### Expected behaviour
No security issues due to vulnerable libraries
### Actual behaviour
Known vulnerabilities in the org.codehaus.plexus:plexus-utils package. This does not include vulnerabilities belonging to this package’s dependencies.

**Comment by Godin** [comment]
First of all, what vulnerability are you talking about exactly? Please provide some references.

Secondly as you can see in https://github.com/jacoco/jacoco/blob/v0.8.8/jacoco-maven-plugin/pom.xml#L51 as of today latest released `0.8.8` version of `jacoco-maven-plugin` already depends on `plexus-utils` version `0.8.22` and not on `0.8.2`.

**Comment by asalsi** [comment]
We see below that version 3.0.22 contains High security flaws
![image](https://user-images.githubusercontent.com/36308756/219061394-89ffec03-6755-4e50-bafc-f78b8a802624.png)


As per Veracode's security analysis we see that the latest clean version is **3.0.24**
![image](https://user-images.githubusercontent.com/36308756/219056276-5323b1ae-be68-44b5-93ed-58f40a7b19cf.png)

Other data points such as https://security.snyk.io/package/maven/org.codehaus.plexus:plexus-utils are a little more forgiving in severity but still show 3.0.24 as the vulnerability free version. 

Our team is unable to use libraries containing medium or higher severities.

**Comment by Godin** [comment]
Still - what vulnerability are you talking about exactly?
If this is about https://security.snyk.io/vuln/SNYK-JAVA-ORGCODEHAUSPLEXUS-461102 then `org.codehaus.plexus.util.xml.XmlWriterUtil` is not used by `jacoco-maven-plugin` as you can see in its code - https://github.com/jacoco/jacoco/blob/v0.8.8/jacoco-maven-plugin/src/org/jacoco/maven/FileFilter.java#L20-L21

Also I do not know how you use `jacoco-maven-plugin` and why its dependency ends up being in your `BOOT-INF/lib`, which looks fishy to me - maybe this is not at all because of `jacoco-maven-plugin` plugin. 

In any case you can update dependencies of Maven plugins without their releases - see https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_dependencies_Tag :

> Using the <dependencies> tag you could configure the dependencies of the Build plugins

More specifically:

```
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-utils</artifactId>
              <version>3.0.24</version>
            </dependency>
          </dependencies>
        </plugin>
      </plugins>
    </pluginManagement>
```

Have you tried this?
