### ISSUE TITLE
Maven 4 compatibility / Maven 3.9 warnings

### ISSUE THREAD

**Issue by OrangeDog** [jacoco/jacoco#1435]
Maven 3.9.2 reports the following issues:

```
[WARNING]  * org.jacoco:jacoco-maven-plugin:0.8.10
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin mixes multiple Maven versions: [3.0, 2.0.2]
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-repository-metadata:3.0, org.apache.maven:maven-artifact:3.0]
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
```

**Comment by ascopes** [comment]
Reproduce this by setting:

```
MAVEN_OPTS+=" -Dmaven.plugin.validation=verbose"
```

**Comment by Godin** [comment]
@marchof AFAICS this is caused by transitive dependencies of `org.apache.maven.shared:file-management:1.2.1`, which is used by our `MergeMojo`

```
[INFO] +- org.apache.maven.shared:file-management:jar:1.2.1:compile
[INFO] |  +- org.apache.maven.shared:maven-shared-io:jar:1.1:compile
[INFO] |  |  +- org.apache.maven:maven-artifact:jar:3.0:compile
[INFO] |  |  +- org.apache.maven:maven-artifact-manager:jar:2.0.2:compile
[INFO] |  |  |  \- org.apache.maven:maven-repository-metadata:jar:3.0:compile
[INFO] |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:1.0-alpha-6:compile
[INFO] |  \- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9:compile
[INFO] |     +- junit:junit:jar:4.13.1:compile (version managed from 3.8.1)
[INFO] |     |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |     \- classworlds:classworlds:jar:1.1-alpha-2:compile
```

however seems that these transitive dependencies are not needed - I drafted exclusions in #1438 and all tests pass.

Another option to solve this - is to update `org.apache.maven.shared:file-management` to version `3.1.0`, but it requires Java 8, whereas `jacoco-maven-plugin` currently requires Java 5.

@marchof WDYT? maybe it's time to require Java 8 for the execution of `jacoco-maven-plugin` as like all core Maven plugins do nowadays ( see https://maven.apache.org/developers/compatibility-plan.html and https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven-dist-tool/job/master/530/site/ ) ? note users still will be able to execute tests with lower Java versions using `maven-toolchains-plugin`.

**Comment by OrangeDog** [comment]
> maybe it's time to require Java 8

I agree. Most stuff already requires Java 11 by now.

**Comment by hazendaz** [comment]
Who is using java 5?  Java 8 at very minimum should be required.  Do note when updating to file-management, if you pass a logger to it from maven itself, call the constructor instead as it uses slf4j internally which conflicts with how maven has that obfuscated.

**Comment by joergsesterhenn** [comment]
@Godin Any idea when this will be released?

**Comment by OrangeDog** [comment]
Just to confuse matters, Maven 3.9.3 has a bug that means it fails to detect issues in this plugin.
https://issues.apache.org/jira/browse/MNG-7826
