### ISSUE TITLE
Option to ignore simple setters/getters and simple constructors

### ISSUE THREAD

**Issue by rbutenuth** [jacoco/jacoco#204]
There should be an option to ignore setters/getters  and simple constructors (no args, no code inside) from the coverage analysis. 

Reason: It makes no sense to test these, but they destroy your metrics.

How to define "simple getter":
Contains a return statement of a field, name of method equal to field method with "get" in front plus first letter of field name capitalized.

How to define "simple setter":
On arg, one assignment to field, method name equal to field name with "set" in front plus first letter of field name capitalized.

How to define "simple constructor":
No arguments, no code inside

**Comment by Balnaz** [comment]
I have same issue

**Comment by sta-szek** [comment]
I was facing similar problem - testing simple methods like getters, setters, constructors and toString to improve coverage report. The problem was the build was failing whe coverage decreased and testing private construcotrs introduced funny code 😆 
I've added testing equals and hashcode method and [pojo-tester](http://pojo.pl) framework was born
