### ISSUE TITLE
Coverage of synchronized block inaccurate?

### ISSUE THREAD

**Issue by brettwooldridge** [jacoco/jacoco#245]
I do not know if it is because of a synchronized block, but the coverage report for this method shows 90%:

![screen shot 2014-10-13 at 8 40 09 pm](https://cloud.githubusercontent.com/assets/1538661/4612844/e951ef2e-52cd-11e4-9f46-188ea6a5c14b.png)

Despite the fact that it is 100% covered, as far as I can tell.  Issues like this are keeping my coverage under the 90% threshold.  This is under JDK 1.8.0_05-b13.

**Comment by jbennett2091** [comment]
You can actually get synchronized-blocks to 100% (instruction, line, branch) with jacoco 0.7.5 (perhaps earlier ones too).   In order to do so, you need two tests:
1.) A test that executes the synchronized block normally.  e.g. above indicates you have that one.
2.) A test that throws an exception from within the synchronized block.   e.g. add a test that causes MultiPoolKey.get(..) to throw IllegalStateException and annotate the test to catch it "@Test(expected=IllegalStateException.class)"
