### ISSUE TITLE
Run CI build with Java 1.5?

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#277]
Hi Evgeny,

I just realized that Cloudbees now seems to offer JDK 1.5. As this is the minimum runtime version for JaCoCo can't we use if for the snapshot builds?

**Comment by Godin** [comment]
@marchof What you see is probably not because of Cloudbees, but a result of my earlier attempts to use JDK 5 for compilation and testing during deployment :) And I've completed this now, so that JDK 5 was used for compilation and testing of latest deployed snapshot and will be used for all subsequent.

**Comment by marchof** [comment]
Thanks, looks great now!
