### ISSUE TITLE
Optimization: Minimize memory footprint by using BitSet instead of boolean[]

### ISSUE THREAD

**Issue by charleswhchan** [jacoco/jacoco#284]
I recently encountered a out of memory problem with running JaCoCo as part of SonarQube analysis, see thread: http://markmail.org/thread/hu6sgl63fdatfno2

From my analysis, it looks like SonarQube's [ExecutionDataVisitor](https://github.com/SonarSource/sonar-java/blob/5d0a4863d95e70ee9d694eb344bb9159dca4ce92/java-jacoco/src/main/java/org/sonar/plugins/jacoco/ExecutionDataVisitor.java) tries to load the results of the analysis into memory. I find that it is is consuming over 2GB of RAM for a small 188MB .exec file. 

Looking at the source code for JaCoCo, I see a instances of boolean[] array being used. Eg. in [ExecutionData](https://github.com/jacoco/jacoco/blob/398ee59bebad6835dab57b60157eff16d511709e/org.jacoco.core/src/org/jacoco/core/data/ExecutionData.java#L29). What does the 'probe' represent? Would it make sense to optimize memory efficiency to use [BitSet](http://docs.oracle.com/javase/7/docs/api/java/util/BitSet.html) instead?

If this sounds like a good idea, I can give it a shot.

**Comment by andrioli** [comment]
This is probably a problem related to SonarQube. Sonar collect coverage per unit test. It increase both memory consumption during analysis and also the time executing tests. But it allow you to view how tests are contributing to the code coverage. I don't know how Sonar works internally during analysis. The JaCoCo devs can explain it better to you :)

Anyway, JaCoCo can't use BitSet internally to keep code coverage (due to race conditions in multi-thread applications). But I guess that the **Analyzer** can use other data structure to reduce the memory footprint. WDYT @marchof ?

**Comment by marchof** [comment]
@andrioli The analysis is correct. The execution data even for *very* large projects is still very compact (< 1MB) and can be analyzed with default memory settings.

A exec file of 188MB most likely comes from thousands of per-test sessions. SonarQube's ExecutionDataVisitor seems to keep all of them in-memory. I don't think there is much we can do from the JaCoCo project, please report this issue to SonarQube.

**Comment by charleswhchan** [comment]
Thanks for the time spent answering my question. 

I found [SONARJAVA-767 - JaCoCo Overall sensor should not load coverage per test in memory](http://jira.codehaus.org/browse/SONARJAVA-767). Not sure if it is related, but I added my comments to the tickets.

Cheers.
