### ISSUE TITLE
Instrumentation should not add methods, this might be critical for Android applications

### ISSUE THREAD

**Issue by byarger-ebay** [jacoco/jacoco#327]
DESCRIPTION:
Jacoco is causing a 10% increase to dex size for Android Studio projects it is applied to. This is an unexpected artifact of including Jacoco, for code coverage, and forces large projects into multi-dexing situations where multi-dexing is otherwise not required.

EXPECTED:

Jacoco should add to the dex count only for the number of methods in the Jacoco agent jar (~1043).

REPRO:

1) Get the dex method count for your project prior to adding Jacoco. I'm using the dex-method-counts project https://github.com/mihaip/dex-method-counts

2) Modify build.gradle as follows:

add: apply plugin: 'jacoco'
Under build types > debug add : testCoverageEnabled true

3) Rebuild the app.

4) Get the dex count again and observer the increase.

**Comment by Godin** [comment]
@byarger-ebay your message contains mix of terms "size" and "number of methods", which IMO require clarification before jumping into investigations of reproducers and so on:
 1. In order to compute coverage JaCoCo inserts probes into bytecode (as well as other all known to me coverage tools). We try to insert as little as possible probes with a little size of each, but in general increase of size (compared to non-instrumented version) is unavoidable.
 2. Also JaCoCo inserts one static initialization method into each instrumented class, so that supposed that total number of methods will increase exactly on total number of classes. This might be possible to avoid and we have some discussions regarding this.

So are you talking about overall size (case 1) or about particular increase of number of methods (case 2)?

**Comment by byarger-ebay** [comment]
Thanks for the clarification. Case 2 is the concern. One of our projects has 1021 classes, which means there are now 1021 new methods that we weren't expecting.

**Comment by Godin** [comment]
So this clearly relates to discussion in #296 , CC @marchof

**Comment by byarger-ebay** [comment]
Is there any update on when this issue will be resolved?

**Comment by marchof** [comment]
@byarger-ebay JaCoCo is based on class file instrumentation, which means additional code is inserted to record the execution flow. This is not possible without adding code, so you will always see an increase in class files size. The prototype in #296 does not add new methods, but adds a small additional class per instrumented class, which effectively double the number of classes.

So the original request not increasing the class file size is not possible with JaCoCo.
