### ISSUE TITLE
strange coverage calculation, is it correct?

### ISSUE THREAD

**Issue by ritchieGitHub** [jacoco/jacoco#339]
First of all jacoco is great! a very very good tool!

I have a problem with the coverage calculation in a special case:

https://github.com/nom-tam-fits/nom-tam-fits/blob/master/src/main/java/nom/tam/image/comp/gzip/GZipCompress.java

this class will show good coverage in coveralls.io based on the data from jacoco: 

https://coveralls.io/builds/3423010/source?filename=src%2Fmain%2Fjava%2Fnom%2Ftam%2Fimage%2Fcomp%2Fgzip%2FGZipCompress.java

but in the site the calculation says:
```
decompress(ByteBuffer, byte[])	3040	57%	75	42%	5	7	0	8	0	1
compress(byte[], ByteBuffer)	3018	38%	62	25%	4	5	0	4	0	1
createGZipInputStream(ByteBuffer)	14	100%		n/a	0	1	0	1	0	1
createGZipOutputStream(byte[], ByteBuffer)	12	100%		n/a	0	1	0	1	0	1
GZipCompress()	3	100%		n/a	0	1	0	1	0	1
Total	60 of 147	59%	13 of 20	35%	9	15	0	15	0	5
```
my test-cases cover everything I can think of, but probably something is missing ;-) 

can you give me a pointer how to get 100% ?

**Comment by Godin** [comment]
Hi @ritchieGitHub , 

the data you provide is super hard to read due to missing formatting and names of columns. Wild guess - this might be related to the fact that try-with-resource is a syntactic sugar for which javac generates additional branches ( see #82 ).

P.S. This is issue tracker, not support forum, please use Users Mailing List in future for questions - http://www.eclemma.org/jacoco/trunk/doc/support.html

**Comment by andrioli** [comment]
note: other factor for different results is the fact that coveralls don't
report branch coverage.
