### ISSUE TITLE
Jacoco Code Coverage for subsequent statement

### ISSUE THREAD

**Issue by vipulbansal91** [jacoco/jacoco#343]
Hi,

I have a code as follows:

void foo1() {
foo1();
foo2();
foo3();
}

void foo1() {
..
...
..
throw new Exception();
}

void foo1() {
if(some condition) {
...
..
throw new Exception();
}
}

void foo2() {
if(some condition) {
...
..
throw new Exception();
}
}

void foo3() {
if(some condition) {
...
..
throw new Exception();
}

}

I have written test case for foo() which are executing the statements in foo1() , foo2() and foo3(), but not in foo().

As per http://www.eclemma.org/jacoco/trunk/doc/flow.html, section "Additional Probes Between Lines"  the probes should be present in foo() after calls to foo1(), foo2() and foo3()?

So I think that the statements under foo() should be shown as covered? Is my understanding correct?

Thanks in advance,

**Comment by marchof** [comment]
Not sure what the question is (where is method foo() in your example?). But yes, since the latest release 0.7.5 we show all lines covered up to (but excluding) lines with implicit exceptions,

Please consider using our mailing list for questions, this is a bug tracker: https://groups.google.com/d/forum/jacoco
