### ISSUE TITLE
Executed code not showing up as being covered

### ISSUE THREAD

**Issue by marcphilipp** [jacoco/jacoco#370]
We are using JaCoCo 0.7.4 for JUnit 5 through the Gradle plugin here:
https://junit.ci.cloudbees.com/job/JUnit5/768/artifact/repo/junit-tests/build/reports/jacoco/junit5CodeCoverageReport/html/index.html

At the moment, we're having a problem with code that JaCoCo reports as not being covered but there clearly is a test that executes it. 

---

To demonstrate the problem and eliminate our setup as potential source of the problem I've created a small [sample project](https://github.com/marcphilipp/jacoco-example) which uses the 0.7.5 Maven plugin. The method `fail(Supplier)` is [called from the test](https://github.com/marcphilipp/jacoco-example/blob/master/src/test/java/org/junit/gen5/api/AssertionsTest.java#L35), but JaCoCo reports it as not being covered:

<img width="650" alt="bildschirmfoto 2016-01-27 um 20 25 16" src="https://cloud.githubusercontent.com/assets/214207/12625611/dcb9cb1c-c534-11e5-8568-cf993eafcf51.png">

---

Is this behavior to be expected? If so, why?

**Comment by marchof** [comment]
This is a limitation of the implementation of JaCoCo. Please see [FAQ](http://eclemma.org/jacoco/trunk/doc/faq.html):

**Source code lines with exceptions show no coverage. Why?**

JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.

**Comment by marcphilipp** [comment]
Thanks for your quick response!

Why does it work for `fail(String)` but not for `fail(Supplier)`?

**Comment by marchof** [comment]
Because `fail(String)` has en explicit throws statement. This is recognized by JaCoCo and handled like a return statement.
In `fail(Supplier)` JaCoCo only sees a method invocation.

**Comment by Godin** [comment]
Hi @marcphilipp ,

already existing improvement for the case of exceptions (#310) does not cover this case unfortunately, since it marks lines above the line with call of method that throws exception. So I've been thinking about further improvements.

Possible to imagine that in given case JaCoCo will report (with all the consequent effects on counters):
```
void fail(Supplier<String> messageSupplier) {
  fail(nullSafeGet(messageSupplier)); // green = covered
} // red = uncovered
```
`}` will be marked as not covered, respecting actual flow of execution and instructions, because method contains `return` instruction that is never executed and control is never returned to a method due to exception.
Referring to your Clover report (junit-team/junit5#240) - IMO questionable why Clover marks method as fully covered.
And actually IntelliJ IDEA code coverage tool produces the same result:
![intellij](https://cloud.githubusercontent.com/assets/138671/21297011/42511a4a-c578-11e6-99a9-75c5086a1329.png)
And Cobertura:
![cobertura](https://cloud.githubusercontent.com/assets/138671/21297012/47512cc4-c578-11e6-8ba7-d792c409e94c.png)
Not tested, but most likely also JCov from OpenJDK.

From the above - question: will this new behavior be acceptable for you? or let's say more acceptable than current? Or the game isn't worth the candle (not worth the efforts) and you'll still be rejecting usage of JaCoCo because of this? Note that I'm not trying to convince you to use JaCoCo, but as was said at the very beginning - just trying to understand the whole story to make improvements.

Could also be noted that idiom
```
RuntimeException create() {
  return new RuntimeException();
}

void fail() {
  throw create();
}
```
is the only one that absolutely unquestionable and formally (in terms of execution and instructions) allows to get rid of uncovered code in such case. And for all tools mentioned above. And even for the current version of JaCoCo and hence in Eclipse with EclEmma. One could even say that it makes code cleaner by clearly stating in the body of a method that it always throws an Exception. So from here IMO such change doesn't look like a workaround (referring to https://github.com/junit-team/junit5/issues/240#issuecomment-217523641) and moreover will allow to make report consistent between various tools available for developers such as their favorite IDE.


Also again referring to junit-team/junit5#240 that states

> Assertions class having a very poor coverage

and

> I want a coverage tool I can trust

that look like a too strong statements, if it is only about single method and single case. I'm wondering if you had other interesting examples/problems? We'd be really glad to hear about them.

Thanks.

**Comment by marcphilipp** [comment]
@Godin Thanks for looking into possible solutions!

> `}` will be marked as not covered, respecting actual flow of execution and instructions, because method contains `return` instruction that is never executed and control is never returned to a method due to exception.

What's really nice about Clover is that it collects the coverage of one's _source_ code, i.e. the smallest unit is Java statements, instead of one's byte code where the smallest unit is byte code instructions. This way, there's no gap when looking at a coverage report. I am certainly aware that this is not an option for JaCoCo and for good reasons. However, I wonder if there's a way to better visualize this in a JaCoCo report, e.g. by adding the possibility to look at the coverage of a method's byte code or showing some inline help for lines such as `}`.

> will this new behavior be acceptable for you? or let's say more acceptable than current?

Yes, that makes much more sense!

> Could also be noted that idiom
> 
>     RuntimeException create() {
>       return new RuntimeException();
>     }
> 
>     void fail() {
>       throw create();
>     }
> is the only one that absolutely unquestionable and formally (in terms of execution and instructions) allows to get rid of uncovered code in such case. And for all tools mentioned above. And even for the current version of JaCoCo and hence in Eclipse with EclEmma. One could even say that it makes code cleaner by clearly stating in the body of a method that it always throws an Exception.

It's worth considering. When you have many overloaded versions of `fail()` it might make the code a bit error-prone because someone might forget the additional `throw`. Moreover, tools like Checkstyle might then barf at you because there are some rules that check that method do not return exceptions.

> I'm wondering if you had other interesting examples/problems?

We only had problems with methods that throw exceptions and other methods that call those. Other than that JaCoCo worked just fine.

**Comment by Godin** [comment]
@marcphilipp Thank you for the information. I'll keep you posted about progress on this, of course only if you're interested.

**Comment by marcphilipp** [comment]
> I'll keep you posted about progress on this, of course only if you're interested.

Please do! 👍

**Comment by C-Otto** [comment]
@marcphilipp @Godin As already documented in https://github.com/jacoco/jacoco/pull/310#issuecomment-103240505 in my original PR I considered this case by indicating that a method invocation that leads to an exception using yellow markers. Maybe it's a good idea to re-think the choice made back then - I obviously like my PR.

**Comment by Godin** [comment]
@C-Otto thank you for your comment and don't worry - fact of existence of your implementation is still kept in my mind 😉 
However in general and in case of @marcphilipp in particular - this is not just about highlighting, but also about counters.

**Comment by diegof00** [comment]
mvn clean verify 

/demo-chat/target/site/jacoco/index.html
