### ISSUE TITLE
Option to generate a single HTML report

### ISSUE THREAD

**Issue by viktorbenei** [jacoco/jacoco#472]
This would be especially useful in a Continuous Integration environment.

Right now you have to download the HTML report __and__ the CSS files in order to be able to see the report.

With a single HTML file report, where style definition is included in the HTML instead of in a separate CSS, all you'd have to download is a single file. No need to ZIP the report to transfer it.

Additionally, in CI systems where the HTML file can be viewed without downloading, this would make it super simple to check the report. Depending on how the CI system structures and serves artifacts generated during the build, relative css references might not work without downloading, as the css file is just another artifact, which can have its own URL.

**Comment by Godin** [comment]
JaCoCo report contains not just a single HTML and CSS, but multiple HTML files, multile CSS files, images and JavaScript files all linked by relative paths. So first of all unclear what you want to achieve - single HTML page or embed all resources into all pages? Both cases actually sound strange for my taste. There are many tools that produce reports in a similar way - with resources placed alongside the HTML files. And I wonder if you have an example of tools (more interestingly - coverage tools), which generate a report in a form that you want?

Speaking about CI system: Visual Studio Team Services for example has no troubles with display of HTML that contains relative references to resources, in particular JaCoCo report - see https://blogs.msdn.microsoft.com/visualstudioalm/2015/11/24/testing-java-applications-with-visual-studio-team-services/. Hence this is probably about some concrete CI system and not about all them. BTW about which one? And so if there is limitation in display of reports in this CI system, then why not fix this limitation in a first place instead of fixing potentially many tools?

**Comment by viktorbenei** [comment]
Completely understandable. For an example tool see [xcpretty](https://github.com/supermarin/xcpretty#reporters).

> Hence this is probably about some concrete CI system and not about all them. 

You're absolutely right (I was talking about https://www.bitrise.io), although it's not exactly CI dependent, more dependent on how build artifacts are stored / made accessible.
If the service exposes the artifacts as a directory, relative files are fine. But if you use a storage system like Amazon S3 and use pre-signed URLs for access (e.g. to make the links expiring) that affects the links / it will make relative links unaccessible, unless the link is modified in the source of the report.

> why not fix this limitation in a first place

I'll report & bring this up at bitrise.io ;)

**Comment by Godin** [comment]
@viktorbenei and what about question
> So first of all unclear what you want to achieve - really single HTML file or embed all resources into all HTML files?

**Comment by viktorbenei** [comment]
Something similar to the [xcpretty html output](https://github.com/supermarin/xcpretty#reporters)

**Comment by Godin** [comment]
So to be specific: answer is - everything in a single file.

**Comment by viktorbenei** [comment]
Exactly. That should be possible for all resources (css, js) except for images.

**Comment by viktorbenei** [comment]
Side note: a single file also make searching easier (Cmd+F in the browser)

**Comment by marchof** [comment]
I don't think a single file will be usable for many projects, simply due to its download size. We have JaCoCo reports for projects with > 500,000 LOC.

**Comment by Godin** [comment]
> Side note: a single file also make searching easier (Cmd/Control+F in the browser)

Report contains source files, so search by class name will not be easy - it will be showing references to this class in others, as well as search by fully qualified name - it will be showing imports.

Even if some JavaScript will be added to collapse/expand sources, I agree with @marchof that currently you can easily locate coverage for a single file in a big project, knowing package. But in case of single page you potentially would need to wait loading of all other files.

**Comment by Godin** [comment]
Speaking more about other reports: for example Gradle test report also contains multiple pages.

**Comment by Godin** [comment]
All in all we with @marchof are not convinced in ROI of this change.

Thank you for your understanding.
