### ISSUE TITLE
Support classfiles and sourcefiles in jacoco-maven-plugin:report

### ISSUE THREAD

**Issue by sharwell** [jacoco/jacoco#493]
Currently the jacoco-maven-plugin report goal does not support configuring the `classfiles` or `sourcefiles` properties in the same manner as the jacoco:report Ant task. Since the default configuration for jacoco-maven-plugin is not able to locate a substantial number of these files automatically, it results in a report that is missing coverage for most of our project. The current workaround we're forced to use is using maven-antrun-plugin to generate the jacoco report, [similar to what's described here](https://intellectualcramps.wordpress.com/2012/03/22/jacoco-tycho-and-coverage-reports/).

It would be very helpful if we were able to specify the `classfiles` and `sourcefiles` configuration properties with the jacoco-maven-plugin rather than using this workaround.

**Comment by Godin** [comment]
@sharwell I'm wondering which `classfiles` and `sourcefiles` can't be found? I'm asking, because within a single module `jacoco:report` is able to find all compile source roots and all the classes that are in directory `${project.build.outputDirectory}` respecting Maven conventions. And for aggregated reports that cross boundaries of modules there is [`jacoco:report-aggregate`](http://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html). IMO ability to specify arbitrary directories is against Maven conventions and principles and won't be different from usage of `maven-antrun-plugin`.

**Comment by sharwell** [comment]
Our sources and tests are in different maven artifacts. The test artifact lists the sources as a dependency in the multi-module build.

**Comment by Godin** [comment]
@sharwell use `jacoco:report-aggregate`. As an example - build of JaCoCo itself contains tests and sources in different modules and uses `report-aggregate`.

**Comment by sharwell** [comment]
:question: Is the report goal able to find all test compile source roots? It seemed that some of the sources in `${project.build.directory}/generated-test-sources/toolName` weren't getting located as well.

**Comment by Godin** [comment]
> generated-**test-sources**

You're right - it locates main source roots, there is already open ticket about generation of report with sources for tests - #271

**Comment by sharwell** [comment]
I tried using report-aggregate instead of report. The resulting report includes coverage information for the dependencies, but not for the main project which references those dependencies. If I use both report and report aggregate, I get one report that contains the main project coverage and another that contains the coverage in dependencies, but neither report shows the combined coverage resulting from running the tests.

**Comment by Godin** [comment]
Looks like #430
Introduction of a dedicated module for generation of report allows to overcome this.

**Comment by sharwell** [comment]
I ran a test with report-aggregate on our other project (it's a slow build), and the results weren't nearly as promising. This project is an Eclipse Tycho build, which uses MANIFEST.MF to specify dependencies as bundles instead of using the `<dependencies>` element in Maven. For an Eclipse Tycho build, the report-aggregate shows up as just empty.

**Comment by Godin** [comment]
@sharwell  last time I tried with Tycho-based project ( on https://github.com/eclipse/eclemma actually ) there were no troubles, so please provide reproducer.

> which don't and can't use a standard Maven structure

I consider that Tycho isn't such case, i.e. structure is indeed a bit different, but still Maven. So let's start not from a solution, but from identification of a problem based on your reproducer.

Blind resolution of _request_ IMO adds more chaos and opens doors for increasing usage of non-standard. And once again - in such case there won't be much difference with usage of `maven-antrun-plugin`.

**Comment by sharwell** [comment]
I'm looking at the eclemma project to see if it's doing anything different. I can't find any references in the project or in the [build output](https://travis-ci.org/eclipse/eclemma/jobs/202142118) indicating that the report or report-aggregate goal is running. Is that part somewhere else?

**Comment by Godin** [comment]
@sharwell I haven't said that it is in place - just "tried" some time ago. Can do this again, but not right now, a bit later.

And it is not in place, because we can see coverage at https://sonarqube.com/dashboard?id=org.eclipse.eclemma%3Aeclemma And BTW I believe that SonarQube uses exact same Maven mechanics to obtain directories as `jacoco-maven-plugin:report-aggregate`.

**Comment by Godin** [comment]
@sharwell branch with example of usage  -
https://github.com/Godin/eclipse-eclemma/tree/jacoco-maven-plugin-report-aggregate 
`mvn clean install` will generate report in directory `org.eclipse.eclemma.site/target/site/jacoco-aggregate`

**Comment by sharwell** [comment]
Thanks for the example, it does show how the tycho dependency issue was worked around. We may try this approach sometime after #271 is fixed.

**Comment by Godin** [comment]
> an entire separate Maven artifact in the build would be created and maintained only for the purpose of feeding information to report-aggregate

>  We could avoid the complexity of an additional artifact in non-tycho projects with #430 fixed, but for tycho projects that approach won't work.

Updated https://github.com/Godin/eclipse-eclemma/tree/jacoco-maven-plugin-report-aggregate to demonstrate that no additional modules is required - report can be created in an existing module that contains tests even in case of Tycho.

> We may try this approach sometime after #271 is fixed

Out of curiosity - how you use reports for code of tests?

> I'm not sure it will be any less complex an approach than our current use of maven-antrun-plugin

As was said multiple times - even addition of `classfiles` and `sourcefiles` configuration properties as proposed won't be any simpler than usage of `maven-antrun-plugin`.

**Comment by sharwell** [comment]
> Out of curiosity - how you use reports for code of tests?

Our primary use of JaCoCo is as an aid to code review. Our application involves a large amount of asynchronous code, and in some cases it's very easy to accidentally write a test because a would-be failing assertion is not actually executed during the test sequence for some reason. For production code, we're looking for high coverage of items changed by a pull request. For test code, we're using the reports to identify cases where a new test did not actually execute code which was expected to execute for the test.

**Comment by jgeorgeson** [comment]
@Godin I'm curious why we still have to specify the test bundle's fragment host as pom dependency for the reporting to work. The effective pom of an eclipse-test-plugin does list the fragment-host as a dependency, and it appears that the jacoco libraries are now themselves OSGi compliant.

Would you consider enhancing the JaCoCo Maven plugin to recognize the Fragment-Host of an eclipse-test-plugin project in order to get the reports to function without the redundant dependency declaration in the pom.xml? Tycho has supported pom-less builds since 0.24 and Maven 3.3.1. So people who are using that feature can't use the report-aggregate goal.

**Comment by Godin** [comment]
@jgeorgeson I don't know details of pom-less implementation in Tycho and had no time/opportunity to have a look. Feel free to investigate, tell us back, provide patch, etc.
