### ISSUE TITLE
Ability to disable cyclomatic complexity analysis

### ISSUE THREAD

**Issue by sharwell** [jacoco/jacoco#494]
We're using JaCoCo 0.7.9 with codecov.io as an aid to our code review process. We're finding that the cyclomatic complexity information isn't necessary for our work, and would like to disable it. The specific benefits we're hoping for from this change are:

1. Reduced test execution time when JaCoCo is enabled (unknown what impact complexity analysis has on this)
2. Reduced report size (the reports are very large currently, and eliminating a piece of unused information would hopefully reduce the size of data being sent over the network for analysis)
3. Reduced coverage report analysis time, primarily as a result of item 2

**Comment by Godin** [comment]
> The specific benefits we're _hoping_ for from this change

First of all when talking about performance - please do measurements and investigations instead of proposing changes out of wild guesses.

> test execution time when JaCoCo is enabled (_unknown_ what impact complexity analysis has on this)

Computation of complexity metric is not performed at runtime during execution of tests, but during analysis of classes at time of generation of report. Thus it has absolutely zero impact on tests execution time.

Analysis of about 23000 OpenJDK classes for generation of report requires about 6 seconds on my laptop. This is about 3800 classes per second, which is very good speed and much faster than build of such big project and execution of its tests. And so IMO disabling of computation of complexity here will be a useless micro-optimization.

> eliminating a piece of unused information would _hopefully_ reduce the size of data being sent over the network for analysis

AFAIK codecov.io consumes XML report. And again on example of OpenJDK - information about complexity contributes just 1% into size of XML. So until proven otherwise by measurements, IMO again an example of micro-optimization.

To measure impact on data transfer and analysis of report on the side of codecov.io you can do postprocessing of XML and remove complexity counters by simply using `sed`. Or use JaCoCo APIs to generate report in any format you want - see `ReportGenerator.java` in examples in our documentation at page http://www.jacoco.org/jacoco/trunk/doc/api.html

And also I'll leave as an exercise an open question of whether there is compression during sending of data or not. But if not, then I would advise to put efforts and hopes in this direction.

All in all - there is no rationale which justify customizability and hence increased complexity of configuration on a side of users and development efforts followed by maintenance on our side.

Thank you for your understanding.

**Comment by sharwell** [comment]
> First of all when talking about performance - please do measurements and investigations instead of proposing changes out of wild guesses.

We are not set up to perform these tests at the current time, so I knew posting with such limited background information was likely to result in a **wontfix** label.

> Thank you for your understanding.

Yes, the response was very informative with respect to our concerns. Thank you for detailing the information like you did. 👍
