### ISSUE TITLE
Coverage when source is spreaded over mutliplie modules

### ISSUE THREAD

**Issue by H3npi** [jacoco/jacoco#563]
### Steps to reproduce

JaCoCo version: 0.7.9
Operating system: Ubuntu 16.04
Tool integration: Maven and Gradle

Project setup:
root
|- entity module
|- logic module with unit tests
|- rest module
|- client with integration tests

### Expected behaviour
Coverage is generated from all modules

### Actual behaviour
only the entity module is covered, rest is only covered when unit tests cover the code

**Comment by Godin** [comment]
First of all - completely unclear how you configured build of your project.

Assuming that in case of Maven you used `report` goal, then as stated in documentation of goal at page http://www.jacoco.org/jacoco/trunk/doc/report-mojo.html :

> Creates a code coverage report for tests of a **single project**

Thus this is expected and correct behavior that `report` goal generates report for single project.

To have a report that includes classes of other modules within Maven reactor please use `report-aggregate` - http://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html In complex scenarios/setups to have a more fine grained control of what is used (classes, sources) for generation of report consider usage of JaCoCo Ant Tasks - http://www.jacoco.org/jacoco/trunk/doc/ant.html

Since you also mentioned Gradle, should be noted that Gradle plugin is not developed by us. As stated on page http://www.jacoco.org/jacoco/trunk/doc/integrations.html - we provide only core library, Ant Tasks, Maven plugin. So in case of Gradle please contact developers of the Gradle plugin.

Finally: Please carefully read documentation before asking a question. And instead of creation of invalid and incomplete items in issue tracker please ask questions on users mailing list and please make sure to provide **fully complete** example demonstrating your difficulty.

Thank you for your understanding.
