### ISSUE TITLE
Can maven plugin get the 'excludes' property from CMD property

### ISSUE THREAD

**Issue by baifan** [jacoco/jacoco#577]
Out test suit will scan several project, but these projects do not declare jacoco plugin in their poms.
We want to exclude some diff class in diff project.
Can jacoco get the 'excludes' property from CMD property?

Like this
```java
/**
 * A list of class files to exclude from report, separated by commas.
 * They will add to {@link #excludes} attribute.
 */
@Parameter(property = "jacoco.excludes")
private String excludesString;

/**
 * A list of class files to exclude from the report. May use wildcard
 * characters (* and ?). When not specified nothing will be excluded.
 */
@Parameter
List<String> excludes;

@Override
public void execute() throws MojoExecutionException {
  ...           
    if (excludesString != null && excludesString.trim().length() > 0 ){
      if (excludes == null){
        excludes = new ArrayList<String>();
      }
      String[] excludeTokens = excludesString.split(";");
      for (String excludeToken : excludeTokens) {
        excludes.add(excludeToken);
      }
    }
  ...
}
```

**Comment by marchof** [comment]
Please use standard maven mechanics, e.g. define property in common parent POM.

**Comment by Godin** [comment]
Few comments in addition to what @marchof said:
The goal of `jacoco-maven-plugin` is to fully integrate code coverage analysis into project and not just perform one-shot external measurements. Such integration, as many other things in build process, requires proper declaration of `jacoco-maven-plugin` in `pom.xml` and not always possible without it (see #592 as an example). Since in quite a lot of cases modification is required, the value of support of scenarios that do not require modifications is low.
