### ISSUE TITLE
mvn -Djacoco.outputDirectory=./jacoco_ut could not create output directory

### ISSUE THREAD

**Issue by binbjz** [jacoco/jacoco#589]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: jacoco-maven-plugin:0.7.8
Operating system: centos 6.5
Tool integration: Maven/Ant/API/Other

### Expected behaviour
If we specify jacoco.outputDirectory=./jacoco_ut parameter, it should create directory "jacoco_ut" in the current directory

### Actual behaviour
output directory is still target/site/jacoco, output directory could not be redirect to customized the output directory

**Comment by Godin** [comment]
> If we specify jacoco.outputDirectory=./jacoco_ut parameter, it should create directory "jacoco_ut" in the current directory

No it should not, because jacoco-maven-plugin does not define user property named `jacoco.outputDirectory` for goal `report` - see http://www.jacoco.org/jacoco/trunk/doc/report-mojo.html#outputDirectory

> output directory could not be redirect to customized the output directory

Usual way to change of configuration of plugin in `pom.xml` allows to customize output directory and even define property, for example:

```
  <properties>
    <myOutputDirectory>jacoco_ut</myOutputDirectory>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.7.9</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
              <goal>report</goal>
            </goals>
            <configuration>
              <outputDirectory>${myOutputDirectory}</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

**Comment by binbjz** [comment]
TopologyCommon-2.6.0.6
I can define dest file by user property named, for example mvn -Djacoco.destFile=./coverage/jacoco.exec, the command will work well.

**Comment by Godin** [comment]
> I can define dest file by user property named, for example mvn -Djacoco.destFile=./coverage/jacoco.exec, the command will work well.

Yes, because `destFile` in opposite to `outputDirectory` has **user property** - see http://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html#destFile

> For output directory, Why can not we continue to do so?

You asked why `jacoco.outputDirectory` doesn't work and you got exact answer on this question.

If this is a feature/enhancement request to add such property, then this is different story, but in such case in future please take time for proper, explicit and polite formatting of your requests to prevent misunderstandings and avoid guessing. Not even mentioning that before opening such request, search for similar opened ones should be considered.

Also should be mentioned that we have far more important things to do than addition of properties for things that already can be configured in `pom.xml` as was shown above.

**Comment by binbjz** [comment]
ok, thanks a lot!
