### ISSUE TITLE
Zero coverage reported on Eclipse plug-in multi-project with Maven and Tycho

### ISSUE THREAD

**Issue by khatchad** [jacoco/jacoco#615]
### Steps to reproduce
1. Clone https://git.io/vwpaK. 
2. Run `mvn install -Pjacoco`

JaCoCo version:0.7.8
Operating system: Linux
Tool integration: Maven, Tycho

### Expected behaviour
In the HTML reports produced, I expected to see greater than 0% coverage. The reports are in edu.cuny.citytech.defaultrefactoring.tests.report/target/site/...

### Actual behaviour
There is 0% coverage for some unknown reason.

**Comment by marchof** [comment]
@khatchad The repo links gives an 404 error.

**Comment by khatchad** [comment]
@marchof fixed.

**Comment by Godin** [comment]
@khatchad my best guess is that [you set `argLine` for `tycho-surefire-plugin`](https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/8454be26160722b744948176b84a896a044e6cfe/edu.cuny.citytech.defaultrefactoring.tests/pom.xml#L47), so that [modification of `tycho.testArgLine` by `jacoco-maven-plugin` `prepare-agent`](http://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html) has no effect.

**Comment by khatchad** [comment]
That did it! Thanks!
