### ISSUE TITLE
Link to SonarQube project is broken

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#616]
New link to SonarQube is

https://sonarcloud.io/dashboard?id=org.jacoco%3Aorg.jacoco.build

**Comment by Godin** [comment]
Actually even analysis is broken due to https://jira.sonarsource.com/browse/SONAR-9835 and was disabled in https://github.com/jacoco/jacoco/commit/424251f1bc3a6a49488133e9ff7f039d23e32af9 😢

**Comment by marchof** [comment]
Looks like the Sonar issue has been fixed: https://jira.sonarsource.com/browse/MSONAR-164

**Comment by Godin** [comment]
@marchof wow, didn't know about this. From my last discussion with SonarSourcers about analysis failure got impression that this won't be fixed and we'll need to change project layout, but looks like community managed to do what I wasn't able - convince that this is not acceptable :clap: Thanks! :thumbsup:

I re-enabled analysis and fixed link in #694 after quick check that it works fine. Another instance of same link fixed in jacoco/www.eclemma.org#12
