### ISSUE TITLE
Incorrect filter convertor in WildcardMatcher

### ISSUE THREAD

**Issue by alex-konshin** [jacoco/jacoco#671]
There is a bug in https://github.com/jacoco/jacoco/blob/6d4d8530f972162cc3a58e2161cf6e01cc13123e/org.jacoco.core/src/org/jacoco/core/runtime/WildcardMatcher.java#L49-L50

It incorrectly converts wildcard `?` into `.?` but it should be just `.`

**Comment by marchof** [comment]
Correct, `?` matches exactly one character: 

https://en.wikipedia.org/wiki/Glob_(programming)

**Comment by Godin** [comment]
@alex-konshin message of @marchof looks ambiguous, but strongly believe that he agreed and understood that there is bug already after your first message and that's why marked this ticket as such - no need to convince more :wink:

Seems that problem is there [since very first version]( https://github.com/jacoco/jacoco/commit/b8ee4efe9c2ba93485fe5d9e25340113efc2390b#diff-1d7d3ad1c9052350a1bbb7102e8ad19bR56), I suppose that wildcard `?` is rarely used compared to `*` or not used at all (can't imagine good use case), so out of curiosity really wondering how you found this?

**Comment by alex-konshin** [comment]
I just tried to understand why pattern *?Resource does not work as I expected.

Actually if you want more explanation then I can provide my feedback and proposal.

First of all, there is no clarification anywhere about the real syntax of filters. For example, just after looking into source code I realized that the convertor replaces all '.' to '/' and this is the reason why some examples on Internet are with dots while others are with slashes. 

In my case I needed to exclude instrumentation of some classes that contains "Resource" but not all of them. The code is not mine and this is really big project (hundreds of thousands files). So, changing or renaming is impossible. Currently I probably found another solution (still need to check) but there are other cases.

I have a proposal. The easiest way to remove the limitation of the current syntax of filters is to allow to use regexp if user really wants it. For backward compatibility you can use the same trick as I did in some my project. The rule is simple: if filter string starts with ^ then we deal with regular expression and WildcardMatcher should take it as is. Otherwise it should use the old converter.

BTW, actually the reason why I have to filter these classes is reflection (yes, I know but this is not my code). And the root cause of the problem was that JaCoCo instruments classes with no code in it (no methods at all). Basically these classes contain just static fields with annotations.  I think it does not make sense to inject counters in such classes.

**Comment by marchof** [comment]
@alex-konshin Thanks for the detailed feedback! I suggest that we fix the glob pattern as a first step.

When introducing regex we should keep an eye on #34.

Please open a separate issue describing the situation of the root cause. I wonder how it is possible to compile classes without code (not even a default constructor). Maybe you can provide an example.

**Comment by alex-konshin** [comment]
Well, probably the class still has default constructor but in this particular case there was the following check (don't ask me why it was there):
`  if (getClass().getDeclaredMethods().length > 0)
       throw new RuntimeException(getClass().getName()+" must not have any declared methods!");`
Obviously it fails after JaCoCo instrumentation. On the other hand it does not make sense to instrument such class.

**Comment by alex-konshin** [comment]
BTW, Regarding this #34. I have my own implementation of converting gitignore-like paths into regexp. They are similar to Ant patterns. Probably it could be adapted to this case if you wish.

**Comment by marchof** [comment]
@alex-konshin What we typically recommend to framework implementors in such situations:

>    if (getClass().getDeclaredMethods().length > 0) throw new RuntimeException(getClass().getName()+" must not have any declared methods!");

Check for non-synthetic methods only! JaCoCo marks its helper method synthetic. There is always a chance that the regular compiler (e.g. in case of inner classes or lambda expressions) adds synthetic methods too.
