### ISSUE TITLE
Does support jetty?

### ISSUE THREAD

**Issue by anymoreT** [jacoco/jacoco#683]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: 0.8.1
Operating system: window/linx
Tool integration: Maven

### Expected behaviour
I run a jetty server and add a jacoco agent for it, then I get the jacoco coverage using maven jcoco plugin.

```
java -jar -javaagent:D:\tools\jacoco0.8.1\lib\jacocoagent.jar=includes=*,output=tcpserver,port=18090,address=127.0.0.1  Mockey.jar
```

mavan pom.xml
```
 <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.1</version>
                <configuration>
                    <append>false</append>
                </configuration>
                <executions>
                    <execution>
                        <id>jacoco-dump</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>dump</goal>
                        </goals>
                        <configuration>
                            <address>${address}</address>
                            <port>${port}</port>
                            <append>${append}</append>
                            <reset>${reset}</reset>
                        </configuration>
                    </execution>
                </executions>

            </plugin>
```

### Actual behaviour
the coverage of code is zero.

**Comment by marchof** [comment]
@anymoreT What do you see when you click on the "sessions" link in the top right corner of the HTML report?

1) Is there at least one session?
2) Are the classes under test listet?

**Comment by anymoreT** [comment]
@marchof  Yes,the classes under test listet,but all classes/method coverage is zero.
I use the jacoco_maven_plugin to dump the jacoco.exec. Then, I import the jacoco.exec to IntelliJ Idea(Anlyze->Show Coverage Data). it show all classes/method/line coverage is zero.  I import another jacco. exec, which is not jetty, and it shows normal data.

**Comment by marchof** [comment]
Ok, in this case you have different classes at runtime than at analysis time. See documentation for details:

**What can cause different class ids?**

Class ids are identical for the exact same class file only (byte-by-byte). There is a couple of reasons why you might get different class files. First compiling Java source files will result in different class files if you use a different tool chain:

- Different compiler vendor (e.g. Eclipse vs. Oracle JDK)
- Different compiler versions
- Different compiler settings (e.g. debug vs. non-debug)

Also post-processing class files (obfuscation, AspectJ, etc.) will typically change the class files. JaCoCo will work well if you simply use the same class files for runtime as well as for analysis. So the tool chain to create these class files does not matter.

Even if the class files on the file system are the same there is possible that classes seen by the JaCoCo runtime agent are different anyways. This typically happens when another Java agent is configured before the JaCoCo agent or special class loaders pre-process the class files. Typical candidates are:

- Mocking frameworks
- Application servers
- Persistence frameworks


https://www.jacoco.org/jacoco/trunk/doc/classids.html
