### ISSUE TITLE
Unable to attach jacoco agent at Runtime using java.lang.instrument API

### ISSUE THREAD

**Issue by RanadheerMusham** [jacoco/jacoco#715]
Unable to attach jacoco agent at runtime using the java.lang.instrument API.

Consider the following usage:

https://blogs.sap.com/2016/03/09/java-bytecode-instrumentation-using-agent-breaking-into-java-application-at-runtime/

This line is getting failed as there is not `Agent-Class` entry in the `Manifest` file.

```
VirtualMachine jvm = VirtualMachine.attach(jvmPid);
jvm.loadAgent(agentFile.getAbsolutePath());
```

Also if I manually added the entry in the manifest (used the PreMain class), loading the agent is getting failed. Because loading the agent requires` public agentmain(final String options, final Instrumentation inst)` method in PreMain class which is missing.

I feel these changes should be brought into the next release to make the distribution compatible with java.lang.instrument API.

**Comment by Godin** [comment]
Attachment of agent to a running JVM is far more complex than you think - not just about `agentmain` and `Manifest`, because there are JVM limitations regarding tranformations for already loaded classes, which are not compatible with the way JaCoCo instruments classes - see #10

> I feel these changes should be brought into the next release to make the distribution compatible with java.lang.instrument API.

`java.lang.instrument` API does not require all agents to implement this feature - quoting https://docs.oracle.com/javase/10/docs/api/java/lang/instrument/package-summary.html :

> If an implementation supports a mechanism to start agents sometime after the VM has started then this attribute specifies the agent class.
