### ISSUE TITLE
Maven Plugin does not work with Travis

### ISSUE THREAD

**Issue by adamretter** [jacoco/jacoco#736]
I followed the examples for configuring JaCoCo, however it seems to cause problems when running our build from Travis-CI. Travis CI is executing the following command initially:
```
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
```

This results in:
```
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.1:check (default-check)
on project j8fu: The parameters 'rules' for goal org.jacoco:jacoco-maven-plugin:0.8.1:check
are missing or invalid -> [Help 1]
```

I don't really understand why JaCoCo is trying to execute when tests are skipped?

Our `pom.xml` config for JaCoCo looks like:

```xml
<plugin>
    <groupId>org.jacoco</groupId>
    <artifactId>jacoco-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>default-prepare-agent</id>
            <goals>
                <goal>prepare-agent</goal>
            </goals>
        </execution>
        <execution>
            <id>default-report</id>
            <goals>
                <goal>report</goal>
            </goals>
        </execution>
        <execution>
            <id>default-check</id>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by Godin** [comment]
Please read `jacoco-maven-plugin` documentation at https://www.jacoco.org/jacoco/trunk/doc/maven.html
to realize that it doesn't use `skipTests` property.

While [`maven-surefire-plugin` uses `skipTests` property](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#skipTests), `jacoco-maven-plugin` goals `report` and `check` work even if `jacoco.exec` file not produced during execution of `maven-surefire-plugin` but comes from somewhere else. And so there is dedicated property `jacoco.skip` property - [see it for example in documentation of `check` goal](https://www.jacoco.org/jacoco/trunk/doc/check-mojo.html#skip).

In the same documentation you can see that specification of `rules` is mandatory for `check`. And so error message is not at all generated by `jacoco-maven-plugin`, but by Maven, what can be seen by executing it with enabled full stacktraces (`-e` or `--errors`). So either do not execute `check` at all by removing

> ```
>         <execution>
>             <id>default-check</id>
>             <goals>
>                 <goal>check</goal>
>             </goals>
>         </execution>
> ```

or configure it

```
<plugin>
    <groupId>org.jacoco</groupId>
    <artifactId>jacoco-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>default-check</id>
            <goals>
                <goal>check</goal>
            </goals>
            <configuration>
               <rules>
               </rules>
            </configuration>
        </execution>
    </configuration>
</plugin>
```

in this case it will just print warning in absence of `jacoco.exec` due to skipped tests.

----

To completely skip execution depending on `skipTests` property use standard Maven mechanisms such as

setting property `jacoco.skip`:

```
<properties>
  <jacoco.skip>${skipTests}</jacoco.skip>
</properties>
```

or in plugin configuration:

```
<plugin>
    <groupId>org.jacoco</groupId>
    <artifactId>jacoco-maven-plugin</artifactId>
    <configuration>
        <skip>${skipTests}</skip>
    </configuration>
</plugin>
```

or in configuration of individual executions:

```
<plugin>
    <groupId>org.jacoco</groupId>
    <artifactId>jacoco-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>default-check</id>
            <goals>
                <goal>check</goal>
            </goals>
            <configuration>
               <skip>${skipTests}</skip>
               <rules>
               </rules>
            </configuration>
        </execution>
    </configuration>
</plugin>
```

Read more about Maven mechanics in its documentation/guides.

----

> Travis CI is executing the following command initially

Quoting https://docs.travis-ci.com/user/languages/java/#projects-using-maven :

> To use a different command, customize the build step.

for example `.travis.yml` can contain

```
install: mvn install -Djacoco.skip -DskipTests=true -Dmaven.javadoc.skip=true -B -V
```

or even

```
install: true
```

About behavior of Travis please refer to its documentation and support.

----

In future please avoid usage of this **bug tracker** for "help me understand" questions - we have [Users Mailing List](https://groups.google.com/forum/?fromgroups=#!forum/jacoco) and there are even far more wider audience of people on StackOverflow that can answer such questions.

Thank you for your understanding.

**Comment by adamretter** [comment]
Thanks for your comprehensive answer :-)

I has read the docs, but somwhow the solution had still evaded me.

I wonder if it would be sensible to code the plugin so that an empty rules element, has the same effect as an omitted rules element. Perhaps generating a warning instead of an error. This would stop others having the same issue as me, at no loss of functionality or behaviour.

**Comment by adamretter** [comment]
So I tried a few of the above options. None of the following solve the problem:

1.
```xml
<properties>
  <jacoco.skip>${skipTests}</jacoco.skip>
</properties>
```

2. Adding this to my `plugin`:
```xml
<configuration>
  <skip>${skipTests}</skip>
</configuration>
```

Adding the following to each of my `executions` for the `plugin` did work though:

```xml
<configuration>
  <skip>${skipTests}</skip>
  <rules></rules>
</configuration>
```
