### ISSUE TITLE
Invalid missing line coverage in report

### ISSUE THREAD

**Issue by kevcodez** [jacoco/jacoco#751]
### Steps to reproduce

Clone https://github.com/kevcodez/pubg-api-kotlin and run `./gradlew test`. It generates this [Jacoco report](https://gist.github.com/kevcodez/eec43fe9f26868b296d6b391859aa6c2).

JaCoCo version: 0.8.1
Operating system: Mac
Tool integration: Gradle

### Expected behaviour

Missed line coverage in source file is the sum of missed source files in class' methods. See PlayerLogin class in the report.

### Actual behaviour

Sourcefile missed line coverage says zero, even though it should be > 0.

Am I missing something here?

**Comment by marchof** [comment]
Line coverage is the sum of all code with the line. Depending on the syntax and the compiler multiple methods can account to a single line. Due to our definition a line is not covered, if no instruction in this line is executed.

Is your example `getAccountId` and `setAccountId` (both are not executed) overlap with the constructor, which is fully covered. Therefore there lines are counted as covered. In the `line` element you can see how many instructions are covered and missed on every line.

**Comment by marchof** [comment]
BTW, next release of JaCoCo will filter many of the methods which are not present in source but only generated by the Kotlin compiler.

**Comment by kevcodez** [comment]
Thanks for clearing that up. Is there an ETA for the next version of Jacoco @marchof ?

**Comment by marchof** [comment]
Probably these days.

**Comment by Godin** [comment]
Let me clarify/add a bit:

Explanations above are about the fact that multiple methods can share the same line numbers and therefore it is incorrect to compare sum of lines in methods with lines in class or source file.

This is unrelated to

> filter many of the methods which are not present in source but only generated by the Kotlin compiler

because such methods anyway do not have line numbers and that's exactly how they are filtered out - see #689 , so this filter affects counters of instructions and methods, but not lines.

There is another filter - see #707 , it will affect number of instructions and branches in `PlayerLogin  .getAccountId`, but not lines, since again - it has nothing to do with the fact that methods share the same line numbers.

And as visual explanation - here is HTML reports for `PlayerLogin`

with version `0.8.1`

![playerlogin](https://user-images.githubusercontent.com/138671/44368446-232ce680-a4d3-11e8-80c2-26aa6bc8b7a8.png)

and with latest snapshot of version `0.8.2`

![playerlogin](https://user-images.githubusercontent.com/138671/44368459-32139900-a4d3-11e8-9080-5dedafa80b3a.png)

As you can see in both cases number of lines in each of the methods is `1` and sum is correctly not equal to the number of lines in class that is `2`.

Hope this helps.

----

And unrelated note: notice that for this class there is no link to source in HTML report, while there is such link for

![apiexception](https://user-images.githubusercontent.com/138671/44368781-4efc9c00-a4d4-11e8-81c9-08da92501883.png)

This relates to the fact that last one is stored in `src/main/kotlin/de/kevcodez/pubg/exception/ApiException.kt`, while former is in `src/main/kotlin/de.kevcodez.pubg.model/telemetry/events/PlayerLogin.kt`, i.e. sub-directories vs directory with dots. [Integrations provided by us (Ant Tasks, Maven, Command-Line Interface)](https://www.jacoco.org/jacoco/trunk/doc/integrations.html) and also Gradle Plugin (as it uses Ant Tasks) do not support such layouts - see https://github.com/jacoco/jacoco/blob/v0.8.1/org.jacoco.report/src/org/jacoco/report/InputStreamSourceFileLocator.java#L48-L52 And to me unclear why such layout ? Is it something usual for Kotlin ?

**Comment by kevcodez** [comment]
@Godin I messed up the directory structure. The layout should just be normal directories, no directories with a dot.

**Comment by Godin** [comment]
@kevcodez you're welcome! and thanks for the information about layout of your packages.

BTW seems that uncovered `PlayerLogin.getAccountId` relates to https://github.com/JetBrains/kotlin/pull/1767
