### ISSUE TITLE
Jacoco maven not recognizing if on public methods

### ISSUE THREAD

**Issue by pedroguibueno** [jacoco/jacoco#770]
### Steps to reproduce

JaCoCo version:  jacoco-maven-plugin 0.8.2
Operating system: Debian
Tool integration: Maven, Jenkins

### Expected behaviour

Jacoco report should recognize if as branchs on public methods. As example, the if in the class below should be recognized and count towards branch coverage

```
public class CobrancaConverter {
   public CobrancaEntity convert(NFeCobrancaEntity cobranca, NfePK nfeKey) {
        if (cobranca == null) {
            return null;
        } else {
            DuplicatasConverter duplicatasConverter = new DuplicatasConverter();
            CobrancaEntity entity = new CobrancaEntity();
            entity.setY03Nfat(cobranca.getNfat());
            entity.setY04Vorig(cobranca.getvOrig());
            entity.setY05Vdesc(cobranca.getvDesc());
            entity.setY06Vliq(cobranca.getvLiq());
            entity.setKey(nfeKey);
            List<CobrancaDuplicataEntity> duplicatas = duplicatasConverter.convert(cobranca.getDuplicatas(), nfeKey);
            entity.setDuplicatas(duplicatas);
            return entity;
        }
    }
}
```

### Actual behaviour

Jacoco isn't recognizing it, the only way i found for it to work was creating a public method that calls the private method. In the example below the if is recognized as branch

```
public class CobrancaConverter {
    public CobrancaEntity converter(NFeCobrancaEntity cobranca, NfePK nfeKey){
        return convert(cobranca, nfeKey);
    }

    private CobrancaEntity convert(NFeCobrancaEntity cobranca, NfePK nfeKey) {
        if (cobranca == null) {
            return null;
        } else {
            DuplicatasConverter duplicatasConverter = new DuplicatasConverter();
            CobrancaEntity entity = new CobrancaEntity();
            entity.setY03Nfat(cobranca.getNfat());
            entity.setY04Vorig(cobranca.getvOrig());
            entity.setY05Vdesc(cobranca.getvDesc());
            entity.setY06Vliq(cobranca.getvLiq());
            entity.setKey(nfeKey);
            List<CobrancaDuplicataEntity> duplicatas = duplicatasConverter.convert(cobranca.getDuplicatas(), nfeKey);
            entity.setDuplicatas(duplicatas);
            return entity;
        }
    }
}

```

**Comment by Godin** [comment]
Answering your question in mailing list (https://groups.google.com/d/msg/jacoco/owUXW45QZjs/QJfVOePwBwAJ):

> Am i doing something wrong?

Yes - you're doing something wrong, because there is no difference between `private` and `public` methods for JaCoCo.

And here is complete example ([example.zip](https://github.com/jacoco/jacoco/files/2487674/example.zip)) that demonstrates branch in public method:

![selection_002](https://user-images.githubusercontent.com/138671/47091052-67fba200-d224-11e8-87e2-e77f246546ed.png)

Can you provide **complete** example that demonstrates your difficulty?

P.S. And no need to create ticket if you didn't received answer on question in mailing list within couple of hours.
