### ISSUE TITLE
Jacoco not ignoring generated lombok @NonNull annotation in coverage reports

### ISSUE THREAD

**Issue by alexandrarprice** [jacoco/jacoco#780]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: 0.8.2
Operating system: osx
Tool integration: Gradle, Lombok

### Expected behaviour

We expect that including lombok.config with lombok.addLombokGeneratedAnnotation set to true would mean that all lombok annotations would be ignored in coverage reports.

### Actual behaviour

When we use the lombok @NonNull annotation, Jacoco reports uncovered branches. We would prefer to keep a high coverage threshold without having to unit test @NonNull.

Attached is a zip that should demonstrate the issue.
[lombok-coverage.zip](https://github.com/jacoco/jacoco/files/2530665/lombok-coverage.zip)

**Comment by Godin** [comment]
@alexandrarprice 

> We expect that including lombok.config with lombok.addLombokGeneratedAnnotation set to true would mean that all lombok annotations would be ignored in coverage reports.

Your expectation is incorrect, since [changelog](https://www.jacoco.org/jacoco/trunk/doc/changes.html) clearly states that **only methods annotated with `@lombok.Generated` are ignored**, which is not the case for the branch introduced by usage of [`@lombok.NonNull` annotation](https://projectlombok.org/features/NonNull), this also has been discussed during implementation of filtering for Lombok - see https://github.com/jacoco/jacoco/pull/495#issuecomment-286358464 and next https://github.com/jacoco/jacoco/pull/495#issuecomment-289863297 .

Moreover the fact that
something is marked as `@lombok.NonNull` and so doesn't require test that it actually can not be null
is IMO highly questionable. @marchof WDYT?

**Comment by marchof** [comment]
@Godin I would go with the same argument we concluded with for Java `assert`: If someone puts it in the code it needs to be tested.

**Comment by Mikhail2048** [comment]
I fully agree with @jordanms. We do not use `@NonNull` as a part of the logic, it should not be tested. It is more for documentation puposes. But in order to satisfy SonarQube quality gate coverage, we are forced to write tests for such cases. 

The other question is how to implement this. But I guess at least such issue should be acknowledged.

**Comment by benketteridge** [comment]
The purpose of using Lombok is to avoid writing boilerplate code. Null checks in an API are boilerplate.
Just like we don't have to write test cases for @EqualsAndHashCode (thank goodness), we rely upon the Lombok project's own unit testing, we should be able to rely on the same for @NonNull.

**Comment by MCEmperor** [comment]
Well, passing null as an argument to a parameter marked `@NonNull` should already trigger an IDE warning. (And if you've using Sonar, it should also complain about it.)

While explicitly testing for null *may* be a good idea, it *may* draw your attention from testing actual logic. It may also be cumbersome to add all kinds of `assertThatNullPointerException().isThrownBy(() -> someMethodCall(null))` tests.

There is an interesting trick employed by Guava (which I found [on Stack Overflow][1]), which hunts for all methods with parameters marked `@NonNull`:

```java
@GwtIncompatible("NullPointerTester")
public void testNullPointers() {
  NullPointerTester tester = new NullPointerTester();
  tester.testAllPublicStaticMethods(Splitter.class);
  tester.testAllPublicInstanceMethods(Splitter.on(','));
  tester.testAllPublicInstanceMethods(Splitter.on(',').trimResults());
}
```

On the other hand, you may also want to avoid to explicitly test for passed `null` arguments when the parameter is marked `@NonNull`.

It may be that JaCoCo will report an uncovered branch when `@NonNull` is used. A solution to this was [posted by evantill][2] here in the comment section:

> If you want to ignore the `@NonNull` annotation in the coverage report you could use the `JDK` exception type in lombok configuration :
> 
> ```ini
> lombok.nonNull.exceptionType = JDK
> ```
> 
> see the lombok documentation on [Supported configuration keys](https://projectlombok.org/features/NonNull#supported-configuration-keys).

That is because by default, Lombok generates a null check like this:

```java
if (parameterName == null) {
    throw new NullPointerException("...");
}
```

and using `lombok.nonNull.exceptionType = JDK` will cause Lombok to generate a call to `Objects#requireNonNull` instead of an `if` check, eliminating the additional uncovered branch.

[1]: https://stackoverflow.com/a/22773112/507738
[2]: https://github.com/jacoco/jacoco/issues/780#issuecomment-1446902948

**Comment by jordanms** [comment]
> > If you want to ignore the `@NonNull` annotation in the coverage report you could use the `JDK` exception type in lombok configuration :
> > ```ini
> > lombok.nonNull.exceptionType = JDK
> > ```
> > 
> >   
> > see the lombok documentation on [Supported configuration keys](https://projectlombok.org/features/NonNull#supported-configuration-keys).
> 
> That is because by default, Lombok generates a null check like this:
> 
> ```java
> if (parameterName == null) {
>     throw new NullPointerException("...");
> }
> ```
> 
> and using `lombok.nonNull.exceptionType = JDK` will cause Lombok to generate a call to `Objects#requireNonNull` instead of an `if` check, eliminating the additional uncovered branch.

Thanks, @MCEmperor, for the explanation. So this is not an actual solution but a hack, as it might change if Lombok team decides to make some changes.
