### ISSUE TITLE
Filtering : Code lines

### ISSUE THREAD

**Issue by Balajinew** [jacoco/jacoco#794]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: 0.8.2
Operating system: Windows
Tool integration: Maven

### Expected behaviour

Skip few lines from class for code coverage via // $COVERAGE-IGNORE$

### Actual behaviour

Code coverage report is not skipping this lines for metrix

**Comment by marchof** [comment]
I assume this is a feature request as this feature is not available as of today. So duplicate to #14.

**Comment by hjohn** [comment]
Just wanted to share my use case for wanting such a feature. First, I'm not aiming for 100% coverage, but there are lines that should never be covered or are uncoverable. Typically these are assertions that would signal a serious problem in the code if they're ever triggered.  If I knew of a way to trigger them (in order to get coverage) that would be a bug and after the bug is fixed they would again be uncoverable.

Some classes can have complicated logic and therefore may have quite a few assertions in them resulting in poor coverage.

Some examples:

    private void removeInternal(T qualifiedType) {
      try {
        for(Class<?> type : Types.getSuperTypes(TypeUtils.getRawType(qualifiedType.getType(), null))) {
          if(type != Provider.class) {
            unregister(type, null, qualifiedType);
  
            for(Annotation qualifier : qualifiedType.getQualifiers()) {
              unregister(type, qualifier, qualifiedType);
            }
          }
        }
      }
      catch(Exception e) {
        throw new AssertionError("Fatal exception (store might be inconsistent) while removing: " + qualifiedType, e);
      }
    }

    private void unregister(Class<?> type, Annotation qualifier, T qualifiedType) {
      Map<Annotation, Set<T>> qualifiedTypesByQualifier = qualifiedTypesByQualifierByType.get(type);
  
      if(qualifiedTypesByQualifier == null) {
        throw new AssertionError("Store must contain: " + qualifiedType + " for class: " + type);
      }
  
      Set<T> qualifiedTypes = qualifiedTypesByQualifier.get(qualifier);
  
      if(qualifiedTypes == null || !qualifiedTypes.remove(qualifiedType)) {
        throw new AssertionError("Store must contain: " + qualifiedType + " for class: " + type + " -> " + qualifier + " qualified types: " + qualifiedTypes);
      }
  
      if(qualifiedTypes.isEmpty()) {
        qualifiedTypesByQualifier.remove(qualifier);
  
        if(qualifiedTypesByQualifier.isEmpty()) {
          qualifiedTypesByQualifierByType.remove(type);
        }
      }
    }

All the above code is called only after making sure all invariants can be met. If this check is buggy, an exception that shouldn't trigger will trigger.  All the catch blocks that throw an `AssertionError` cannot be covered unless:

 - I mock certain stuff to return things they normally never could -- this is bad, as the tests then give the impression that it is actually valid input while it isn't
 - I make the method accessible from outside the class so I can provide it with input it normally could never receive -- bad as I don't want to break encapsulation (even a little) for tests, not to mention that it again would be testing input that is impossible during normal operation
 - I discover a bug in the logic -- such a test would be written, but would also promptly be fixed

I was hoping it would be possible to configure Jacoco to automatically ignore any code blocks (or catch blocks) where an `AssertionError` is thrown.  Something similar applies to the `assert` keyword, except I'm not comfortable using that as the check can be switched off.
