### ISSUE TITLE
Please add support to ignore AvroGenerated annotations

### ISSUE THREAD

**Issue by oasalonen** [jacoco/jacoco#814]
Jacoco already supports ignoring e.g. Lombok Generated annotations. It would be useful to have something similar for [AvroGenerated](https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/specific/AvroGenerated.html) annotations. Since it has RUNTIME retention, this should be possible [unlike the javax Generated annotation](https://github.com/jacoco/jacoco/issues/685).

**Comment by Godin** [comment]
@oasalonen since version 0.8.3 JaCoCo recognizes not only `lombok.Generated`, but any annotation whose simple name is `Generated`, e.g. `avro.Generated` - #731. I discovered Apache Avro just today due to this ticket, however according to https://issues.apache.org/jira/browse/AVRO-1186 seems possible to add any custom annotation to generated classes and if so, then maybe you can simply add `avro.Generated` ?

**Comment by Godin** [comment]
> I'm guessing you meant 0.8.2 since I don't yet see a 0.8.3 release.

Sorry for this typo, yes - I meant already released `0.8.2` 👍 , while was working on preparation of next `0.8.3` :sweat_smile:

> When the avro-compiler generates Java classes, it creates a nested Builder class that does not get the declared annotation, and there doesn't seem to be any way to control which annotations get attached to the builder.

Way to control which annotations get attached to the builder is better (and IMO worth it) to be discussed with developers of Avro.

> The builder then shows up in coverage reports. But this problem could only be solved if JaCoCo ignores nested classes of a top-level class with a `@Generated` annotation.

Even if we'll extend range of accepted annotations, similarly to https://github.com/immutables/immutables/issues/792 nested classes must also be marked with annotation - highly unlikely that notion of nesting will be added to JaCoCo any time soon, because it greatly complexifies many things on our side and we'd really like to avoid this. And especially that javadoc of [`org.apache.avro.specific.AvroGenerated`](https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/specific/AvroGenerated.html) clearly states

> **All** Avro generated classes will be annotated

and nothing about nesting. So please contact developers of Avro also about this.

> There is also a drawback to using a custom Java annotation property in our case: we declare Avro schemas and share them across microservices with a schema registry. If we declare a custom annotation, the annotation needs to be defined in some shared library that gets used by every microservice that uses the schema, increasing coupling between the services.

Sorry, but I don't know what is "schema registry", however AFAIK class files with annotations whose retention policy is [`class`](https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/RetentionPolicy.html#CLASS) doesn't require distribution of annotation itself. Also every microservice can declare its own `avro.Generated` to avoid shared library.

Also should be mentioned that generated classes can be placed into their own dedicated package that can be excluded from analysis.

In any case I created #822 And in the meantime, while maybe being a less convenient, IMO above options are perfectly valid alternatives or at least possible workarounds.

Thank you for your understanding.

**Comment by oasalonen** [comment]
Filed a [bug for the Avro project](https://issues.apache.org/jira/browse/AVRO-2298).
