### ISSUE TITLE
Generated annotation filter detection does not work when used with parameters

### ISSUE THREAD

**Issue by tasomaniac** [jacoco/jacoco#831]
### Steps to reproduce

JaCoCo version: 0.8.2
Operating system: MacOS
Tool integration: Gradle

### Expected behaviour

Class generated with `@Generated` annotation with parameters should also be ignored from code coverage report. 

It is pretty easily reproducable when used by Google's Dagger annotation processor. They put something like below on top of generated classes

```
@Generated(
    value = "dagger.internal.codegen.ComponentProcessor",
    comments = "https://google.github.io/dagger"
)
public final class SomeGeneratedClass
```

### Actual behaviour

Not just simple usage of `@Generated` annotation but all versions should be ignored.

**Comment by Godin** [comment]
Hi,

This has nothing to do with parameters, because as you [can see Google's Dagger annotation processor](https://github.com/google/dagger/blob/e0e47f1bf7ca4a2251427d678c51990aca15c536/javatests/dagger/internal/codegen/GeneratedLines.java#L32-L35) uses either [`javax.annotation.Generated`](https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html) or [`javax.annotation.processing.Generated`](https://docs.oracle.com/javase/9/docs/api/javax/annotation/processing/Generated.html) and  unfortunately **both have [retention policy](https://docs.oracle.com/javase/8/docs/api/index.html?java/lang/annotation/RetentionPolicy.html) SOURCE** (aka discarded by compiler). This has been already discussed many times ( https://github.com/jacoco/jacoco/issues/685#issuecomment-392020612 , https://github.com/jacoco/jacoco/issues/656#issuecomment-373221773 ) and even mentioned in [changelog](https://www.jacoco.org/jacoco/trunk/doc/changes.html) - JaCoCo performs analysis of bytecode and hence **annotation must have retention policy RUNTIME (aka "runtime visible") or CLASS (aka "runtime invisible" yet retained in class files)**.

Annotations with parameters having correct retention policy are processed correctly:

given `src/org/example/Example.java`

```
package org.example;

class Example {

  public void m1() {
  }

  @javax.annotation.Generated("")
  public void m2() {
  }

  @Generated(message = "")
  public void m3() {
  }

}

@java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.RUNTIME)
@interface Generated {
  String message();
}
```

execution of

```
mkdir bin
javac -d bin src/org/example/Example.java
java -jar jacoco-0.8.2/lib/jacococli.jar report --classfiles bin --sourcefiles src --html report
```

produces

![example](https://user-images.githubusercontent.com/138671/51335675-f8938980-1a82-11e9-804d-3c28f8ee55ec.png)

as expected.

**Comment by tasomaniac** [comment]
Thanks for the detailed reply. I actually searched before posting but couldn't find it. 

Here is 2 feedback:

- the docs says Generated annotation is detected if it is visible or invisible. That is kind of confusing. I thought SOURCE retention would mean visible :)

- The source files are available to Jacoco. Would it be possible to read sources to pick up the annotation?

**Comment by Godin** [comment]
> the docs says Generated annotation is detected if it is visible or invisible. That is kind of confusing. I thought SOURCE retention would mean visible :)

Noted, will improve.

> The source files are available to Jacoco. Would it be possible to read sources to pick up the annotation?

No - source code parsing is out of scope of  project, not even recalling/considering that JaCoCo supports Kotlin and Groovy.

**Comment by tasomaniac** [comment]
That makes sense. 😊 Thanks a lot.
