### ISSUE TITLE
Running a coverage of a single test method

### ISSUE THREAD

**Issue by dormaayan** [jacoco/jacoco#843]
Hey,

I want to collect coverage of single test methods (while all the other test methods don't run) over a large corpus of code. Since the corpus is large, I would like to do that automatically.

Is there a way to specify to Jacoco to run only over a single test method and to export the data conveniently in a high resolution (I'm not interested in a lower granularity of coverage per class for example)

Many thanks!

**Comment by Godin** [comment]
First of all there is clear statement that you missed and deleted during creation of this issue, the same statement is in readme:

> This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please do so in future.

Also please do a research before asking questions, because such and [similar questions were already answered many times in past](https://groups.google.com/d/msg/jacoco/m3u0Uw1kjo0/5F3X9GVuBAAJ):

> Is there a way to specify to Jacoco to run only over a single test method

No, because **JaCoCo does not execute tests**.

JaCoCo is completely independent from testing frameworks, it simply records execution. You can:

* instruct your testing framework to execute tests in separate JVM, configure JaCoCo to record their execution into separate exec-files and generate separate reports from them
* or control recording using JaCoCo APIs:
  * via API of JaCoCo agent - https://www.eclemma.org/jacoco/trunk/doc/api/org/jacoco/agent/rt/RT.html
  * via JMX - https://www.jacoco.org/jacoco/trunk/doc/examples/java/MBeanClient.java
  * via sockets - https://www.jacoco.org/jacoco/trunk/doc/examples/java/ExecutionDataClient.java
