### ISSUE TITLE
Shouldn't report-aggregate MOJO be an aggregator mojo?

### ISSUE THREAD

**Issue by JWGmeligMeyling** [jacoco/jacoco#869]
Currently, the `report-aggregate` goal from the `jacoco-maven-plugin` is not specified as an [`aggregator`](https://maven.apache.org/plugin-tools/maven-plugin-annotations/apidocs/org/apache/maven/plugins/annotations/Mojo.html#aggregator--) MOJO. Aggregator executions run once and last, after the submodules have already executed their plugins. Having `aggregator` disabled means that, for multi-module projects this results in the goal being executed for every single module, which is often not what you want. As a work around, examples usually create a separate [`coverage-report` module](https://github.com/jacoco/jacoco/wiki/MavenMultiModule#usage), which is dependent on any other submodule relevant for the results, and only define a plugin execution on that project. This however feels like a workaround to me, and it seems much more logical to me to just declare the `report-aggregate` MOJO as an aggregator and have it only be run once on the entire project anyway.

If we decide to stick with the current behaviour of `report-aggregate`, perhaps we could introduce a new goal `report-aggregator` in a non-breaking fashion. I suppose it would eliminate the need of a separate coverage report module in most cases, and drastically simplify setup.

### Steps to reproduce

JaCoCo version:
Operating system: OSX
Tool integration: Maven

### Actual behaviour

**Comment by Godin** [comment]
Mojos marked as `aggregator` can only be called directly like for example `release:prepare` and `release:perform` ( see https://issues.apache.org/jira/browse/MNG-6336 ), so can't cover all use-cases which `report-aggregate` already covers. Addition of another goal just for direct invocation is counterproductive and misleading.

**Comment by JWGmeligMeyling** [comment]
Ah I see, I actually misread that section of the documentation. I do agree that the current `report-aggregate` goal is more versatile than achievable through aggregator tasks. I do however not agree that having another goal for direct invocation is counterproductive or misleading. It will make the trivial case of a single report for a multi module project a lot easier. Even though the current proces is well documented, there is confusion about it on the internet and it is just tedious to set up the entire module to even get started with multi module coverage reporting.

I've patched the plugin in order to include an aggregator module as I was tidying up my modules anyway. I've opened up a PR with the work I've done, don't feel the urge to integrate it, just wanted to put it out there 😄

**Comment by Godin** [comment]
Thank you for your contribution, however based on our more than 8 years of experience answering various questions in users mailing list regarding various use cases, addition of another goal with very similar name and very subtle and not so easy to understand difference is "misleading" for users and "counterproductive" for us in term of maintenance. Thank you for your understanding.

**Comment by EvgeniGordeev** [comment]
IMO the version of mojo suggested by @JWGmeligMeyling makes more sense. Given other widely used maven plugins like [checkstyle](https://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-aggregate-mojo.html), [dependency-check](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/aggregate-mojo.html) one expects from an aggregate report that reactor modules are taken into account. 
That's quite unpleasant that to use an aggregate task one needs to create another separate module in a multi-module project and support the list of dependencies there which is basically a duplication of what is already defined in reactor pom. In addition you are forced to update the dependencies in your separate module once your reactor pom is updated otherwise your report gets out of sync. 

On the other side having 2 aggregate reports doesn't sound like a great idea for users or maintainers. @Godin is there a chance that a PR implementing @JWGmeligMeyling 's idea can be accepted by Jacoco Team if acceptance criteria are met as follows:

* no new aggregate report is introduced
* `report-aggregate` goal receives a flag `<useReactorModules>` - `false` by default to preserve current behavior.

**Comment by marchof** [comment]
@EvgeniGordeev The main question for us maintainters is: Would you be willing to help with maintainance: Fixing bugs? Answering questions to users?

We simply have no capacity to maintain new functionality.

**Comment by EvgeniGordeev** [comment]
@marchof I'm ready to provide support for `report-aggregate` goal if necessary.  But I still need to prove that the approach with just one more flag `useReactorModules` is feasible and the mojo doesn't get overcomplicated to maintain it.

**Comment by Godin** [comment]
@EvgeniGordeev AFAIK only mojos marked as `aggregator` run once and **last**, such hack as **experimental** option `deployAtEnd` of `maven-deploy-plugin` was already discussed and rejected in past - see https://github.com/jacoco/jacoco/pull/388#issuecomment-200512340 according to which
> the real solution means improving Maven core

**Comment by EvgeniGordeev** [comment]
@Godin you are right, forcing the goal to run last was the second issue on my agenda next after figuring out how to switch `aggregator` mojo attribute programmatically but the latter seems to be impossible due to the way [Mojo](https://github.com/apache/maven-plugin-tools/blob/master/maven-plugin-annotations/src/main/java/org/apache/maven/plugins/annotations/Mojo.java) is converted into [MojoDescriptor](https://github.com/apache/maven/blob/master/maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/MojoDescriptor.java) and later controls `aggregating` flow of a goal execution. 

The idea to simplify the creation of an aggregating report seems still a valid one however I agree that it must not be part of this project due to backward compatibility/maintainability hell maintainers end up in if such a feature is added. Maybe a separate maven plugin with some known limitations like running only in detached mode after module execution files are created or single threaded execution (that was actually the third issue I faced while fiddling with the report-aggregate goal).

**Comment by kwin** [comment]
@Godin The approach for `deployAtEnd` has been streamlined a lot in the past with https://github.com/apache/maven-deploy-plugin/pull/20 and https://github.com/apache/maven-deploy-plugin/pull/34. Now the approach is quite lean with 
https://github.com/apache/maven-deploy-plugin/blob/69626994554a4b85e5928c4cd4ec832b3ee60764/src/main/java/org/apache/maven/plugins/deploy/DeployMojo.java#L227

Would you accept a PR which adds a boolean flag `reactorAggregate` to `report-aggregate` leveraging a similar approach as m-deploy-plugin's `deployAtEnd` which will:
1. Only run it with the last relevant module from the reactor and skip execution for earlier modules
2. Automatically considers all aggregate module execution data files
3. Makes https://www.eclemma.org/jacoco/trunk/doc/report-aggregate-mojo.html#outputDirectory relative to the reactor root (irrespective of what the last module of the reactor is)

That way using this goal does no longer require a dedicated module (https://github.com/jacoco/jacoco/wiki/MavenMultiModule#strategy-module-with-dependencies) for most of the use cases.
