### ISSUE TITLE
Offline instrumentation causes a GC crash on Docker deployment

### ISSUE THREAD

**Issue by zipperHead** [jacoco/jacoco#881]
I have a webapp that I am trying to instrument and deploy using Docker. Jacco agaent is in the deployable 0.8.4, but upon starting the service, I get this memory dump.
I know there is not much repro information here, and I couldn't get more information either, but can I get some help at least to debug this further? This is all the logging  I get.

-XX:GCLogFileSize=10485760 -XX:-HeapDumpOnOutOfMemoryError -XX:InitialHeapSize=524610240 -XX:MaxHeapSize=8393763840 -XX:NumberOfGCLogFiles=5 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseGCLogFileRotation -XX:+UseParallelGC 
Heap
 PSYoungGen      total 150016K, used 18191K [0x0000000719380000, 0x0000000723a80000, 0x00000007c0000000)
  eden space 129024K, 14% used [0x0000000719380000,0x000000071a543e00,0x0000000721180000)
  from space 20992K, 0% used [0x0000000722600000,0x0000000722600000,0x0000000723a80000)
  to   space 20992K, 0% used [0x0000000721180000,0x0000000721180000,0x0000000722600000)
 ParOldGen       total 343040K, used 0K [0x00000005cba00000, 0x00000005e0900000, 0x0000000719380000)
  object space 343040K, 0% used [0x00000005cba00000,0x00000005cba00000,0x00000005e0900000)
 Metaspace       used 3600K, capacity 4564K, committed 4864K, reserved 1056768K
  class space    used 375K, capacity 388K, committed 512K, reserved 1048576K

**Comment by marchof** [comment]
What exactly do you mean by "GC crash"? What does the heap dump contain?

**Comment by zipperHead** [comment]
All the information I got in the loga are in the initial ticket and I assumed it is a crash, because the service didn't start. If I remove the instrumentation step, the service starts fine.

**Comment by Godin** [comment]
@zipperHead IMO log that you show is absolutely normal consequence of your JVM options without any evidence of crash - for example given following `Example.java`

```
class Example {
    public static void main(String[] args) {
        System.out.println("Hello, World!\n");
    }
}
```

execution with option `-XX:+PrintGCDetails` as following

```
javac Example.java
java -version
java -XX:+PrintGCDetails Example
```

produces following output

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Hello, World!

Heap
 PSYoungGen      total 76288K, used 3932K [0x000000076ab00000, 0x0000000770000000, 0x00000007c0000000)
  eden space 65536K, 6% used [0x000000076ab00000,0x000000076aed7240,0x000000076eb00000)
  from space 10752K, 0% used [0x000000076f580000,0x000000076f580000,0x0000000770000000)
  to   space 10752K, 0% used [0x000000076eb00000,0x000000076eb00000,0x000000076f580000)
 ParOldGen       total 175104K, used 0K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 0% used [0x00000006c0000000,0x00000006c0000000,0x00000006cab00000)
 Metaspace       used 2630K, capacity 4486K, committed 4864K, reserved 1056768K
  class space    used 286K, capacity 386K, committed 512K, reserved 1048576K
```

as expected.

Are you sure that Docker (or whatever else you use for deployment) doesn't hide output from you? Have you tried locally without Docker? Can you try?

Also note that usage of offline instrumentation is not recommended and in most cases not needed. One of many reasons of why it is not recommended, is that it requires more complicated setup than usage of agent - for example quoting https://www.jacoco.org/jacoco/trunk/doc/offline.html

> Unlike with on-the-fly instrumentation offline instrumented classes get a direct dependency on the JaCoCo runtime. Therefore `jacocoagent.jar` has to be on the classpath and accessible by the instrumented classes. The proper location for `jacocoagent.jar` might depend on your deployment scenario.

Thus are you sure that you have `jacocoagent.jar` of corresponding version `0.8.4` in your classpath (`-cp` or `-classpath` option)? And why do you use offline instrumentation? What prevents you from simple usage of agent as `java -javaagent:path/to/jacocoagent.jar ...` instead of offline instrumentation?

**Comment by zipperHead** [comment]
@Godin First thank you for your quick response and suggestion. I was writing to tell you that I gave up on the offline instrumentation and used the on-the-fly instrumentation with jacocoagent.jar which works fine, but I wanted to get an answer to why the offline was not working and I was sure that the jacocoagent.jar is on the classpath, though that the error message on the startup of the docker container complained about not finding the jar, and when I tried to repro it for you to get you the exact error message it started working again !!!

If I try the offline again and it doesn't work, I will contact you :) 
Thanks again

**Comment by Godin** [comment]
Thank you for letting us know.
