### ISSUE TITLE
Kotlin properties marked as uncovered when checked through `equals()` method

### ISSUE THREAD

**Issue by lwasyl** [jacoco/jacoco#900]
JaCoCo version: 0.8.4, Gradle

### Expected behaviour
Having simple Kotlin class:
```kotlin
data class KotlinDataClass(
  val parameter: String
)
```
and a test:
```kotlin
@Test
fun testDataClass() {
    val expected = KotlinDataClass("Param")
    val actual = KotlinDataClass("Param")

    assert(expected == actual)
}
```
I would expect that `parameter` property is marked as covered, because its value is verified in `assert(expected == actual)`. But since `parameter` has a backing field, the getter is not used from the `equals` method:
```kotlin
public boolean equals(@Nullable Object var1) {
   if (this != var1) {
      if (var1 instanceof KotlinDataClass) {
         KotlinDataClass var2 = (KotlinDataClass)var1;
         if (Intrinsics.areEqual(this.parameter, var2.parameter)) {
            return true;
         }
      }

      return false;
   } else {
      return true;
   }
}
```

### Actual behaviour

Currently `parameter` property is marked as uncovered by tests:

![image](https://user-images.githubusercontent.com/3951580/59916280-0331c080-941f-11e9-8ca4-d69664e67284.png)

I'm not quite sure how fixable this is in Jacoco. I expect Kotlin can't optimize away the public getter method due to compatibility with Java, which should always use `getParameter()` regardless of whether there exists custom getter.

**Comment by Godin** [comment]
Public properties in data classes do not go alone, i.e. there is code outside of data class that reads this property. And IMO JaCoCo behaves correctly - allows to observe that this read actually happens:

<img width="886" alt="Example_kt" src="https://user-images.githubusercontent.com/138671/59930063-5ff2a280-9442-11e9-8334-3fb0d1a7916d.png">

<img width="885" alt="KotlinDataClass" src="https://user-images.githubusercontent.com/138671/59930071-641ec000-9442-11e9-862b-abbbcf29a702.png">

If there is no external consumers, then make it `private` - it still will be used in `equals`/`toString`/`hashCode`/etc methods, but getter won't be generated:

<img width="886" alt="Example_kt" src="https://user-images.githubusercontent.com/138671/59930080-684add80-9442-11e9-8614-678f6fc2ed7b.png">

<img width="888" alt="KotlinDataClass" src="https://user-images.githubusercontent.com/138671/59930084-6aad3780-9442-11e9-88d6-1a03d40f1792.png">

**Comment by charlesritchea** [comment]
@Godin This is not what I'm seeing at all. I'm explicitly testing the getters and it's still marked as uncovered

**Comment by felix-kaestner** [comment]
@Godin I'm currently facing the same Issue. 
It is unclear to me why I should even test a data class at all if it has no body.

The problem that @lwasyl was facing, is that he will have to access all properties defined within the primary constructor of a data class in order to call all generated getter functions so the test coverage would be 100%.

Your argument was that: 
> If there is no external consumers, then make it private

But that argument is not true in every situation.

In my situation we are working on an android library were all of these properties do not have a external consumer within in the scope of the library but will be called by the android app that will use the library. This results in the fact that I will have to write a lot of meaningless tests in order to get the coverage up. And I'm even unsure why I should validate the _equals_ method, too.

IMHO I should not have to write any tests if I declare a data class without a class body. And if it has a class body I should also only test these functions because they are not implicitly defined by the primary constructor, i.e. generated by kotlin. There is no reason why I as a developer should have to validate that the generated code from kotlin for a data class is working as expected. That is the responsibility of the kotlin authors. And code coverage should not depend on unused statements.

**Comment by FyiurAmron** [comment]
@Godin any update on this, or just the "we closed this, because we don't care about what the users think, WONTFIX, works as expected, not a bug but a feature, and that still stand by that opinion, no amount of arguments or upvotes on anything will change our mind"?
