### ISSUE TITLE
Some branches are not covered if the type of a default argument is Long.

### ISSUE THREAD

**Issue by eungjun-yi** [jacoco/jacoco#907]
### Steps to reproduce

JaCoCo version: 0.8.5-SNAPSHOT
Operating system: Linux pop-os 5.0.0-20-generic
Tool integration: gradle

Test this production code:

```kotlin
data class Foo(val x: Long = 0)
```

by this test:

```kotlin
class FooTest {

    @Test
    fun test() {
        assertEquals(1, Foo(1).x)
        assertEquals(0, Foo().x)
    }
}
```

### Expected behaviour

All instructions and branches are covered

### Actual behaviour

All instructions are covered but 50% of branches are NOT covered.

![image](https://user-images.githubusercontent.com/1129852/61399477-39247080-a909-11e9-9323-273a67d69e27.png)

**Comment by eungjun-yi** [comment]
The branches are covered if the type of the default argument is `Int` or `String`.

**Comment by Godin** [comment]
This happens because [KotlinDefaultArgumentsFilter](https://github.com/jacoco/jacoco/blob/v0.8.4/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilter.java#L71-L72) assumes that all parameters consume one slot, whereas `long` and `double` consume two slots.

@eungjun-yi thank you for reporting this :thumbsup:
