### ISSUE TITLE
Getting issue while generating remote code coverage

### ISSUE THREAD

**Issue by anksngp** [jacoco/jacoco#915]
1. Created one sample Spring boot project with rest controller
2. Trying to run the project within eclipse as a java application
3. Added below args to the runtime args

-javaagent:C:\jacocoagent.jar=port=36320,destfile=jacoco-it.exec,output=tcpserver

4. After the server is started i tried to hit the url via postman to test my application. and got proper expected response.

5. Then i ran the below command to dum data
jacoco:dump@pull-test-data -Dapp.host=localhost -Dapp.port=36320 -Dskip.dump=false

6. Got the below output on console
Dumping execution data to C:\jacoco-it-localhost:36320.exec

but the file generated is of 0 bytes.
 

JaCoCo version: 0.7.5.201505241946
Operating system: Windwows
Tool integration: Maven

**Comment by marchof** [comment]
Our [integration tests](https://github.com/jacoco/jacoco/tree/master/jacoco-maven-plugin.test/it/it-dump) tests show that the `dump` goal basically works.

To investigate your scenario please provide a complete reproducer (preferably as Github repo).

Just one hint: colon is not a valid character  in windows filenames:

    C:\jacoco-it-localhost:36320.exec

Maybe this is the issue?

**Comment by Godin** [comment]
`dump` ( https://github.com/jacoco/jacoco/blob/master/jacoco-maven-plugin/src/org/jacoco/maven/DumpMojo.java#L117 ) writes at least 5 bytes - see https://github.com/jacoco/jacoco/blob/v0.7.5/org.jacoco.core/src/org/jacoco/core/data/ExecutionDataWriter.java#L56-L69

As @marchof said, colon (`:`) in your filename is likely a root of the problem, because it is reserved character - see https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words and https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file

To confirm this, I executed following code on Windows

```
import org.jacoco.core.tools.ExecFileLoader;

class Example {
	public static void main(String[] args) {
		new ExecFileLoader().save(new File("C:\\test\\ok.exec"), true);
		new ExecFileLoader().save(new File("C:\\test\\colon:36320.exec"), true);
	}
}
```

which results in following `dir C:\test` 

```
 Volume in drive C is Windows
 Volume Serial Number is D4AB-4044
 Directory of C:\test
08/07/2019  03:15 AM    <DIR>          .
08/07/2019  03:15 AM    <DIR>          ..
08/07/2019  03:15 AM                 0 colon
08/07/2019  03:15 AM                 5 ok.exec
```

Note that size of a first file is indeed shown as 0, however it's name not at all expected `colon:36320.exec`, whereas second file `ok.exec` has expected size 5 bytes.

P.S. JaCoCo version 0.7.5 is already 4 years old - see https://www.jacoco.org/jacoco/ and https://www.jacoco.org/jacoco/trunk/doc/changes.html

**Comment by anksngp** [comment]
Hi, i am not creating the file name with a semi colon. This is being done by jacoco. If you see my jvm args there is no semi colon anywhere. This was the output on the eclipse console when i ran the dump command.

**Comment by Godin** [comment]
@anksngp you execute

```
mvn jacoco:dump@pull-test-data -Dapp.host=localhost -Dapp.port=36320 -Dskip.dump=false
``` 

which will use following configuration from `pom.xml` ( https://github.com/pszeliga/jacoco-e2e-coverage/blob/2d554ed0f97870c22a124bd13fb5db4b35b69b8d/pom.xml#L60-L64 )

```
<id>pull-test-data</id>
<phase>post-integration-test</phase>
<goals>
	<goal>dump</goal>
</goals>
<configuration>
	<destFile>${project.build.directory}/jacoco-it-${app.host}:${app.port}.exec</destFile>
```

which clearly contains colon `:` after `jacoco-it-${app.host}` and before `${app.port}.exec`.

Same in https://dzone.com/articles/verifying-end-to-end-test-code-coverage-using-jaco
